### PR TITLE
refactor i.landsat.import to use gdal virtual file system and tarfile library

### PR DESCRIPTION
**Pull request by veroandreo**
This PR implements @ninsbl  suggestion in https://github.com/veroandreo/i.landsat/issues/16#issuecomment-742844484 to use GDAL virtual file system and the tarfile library instead of shutil. This removes the need to untar files and then remove them. The `unzip_dir` option is no longer required either.

### CODE REVIEW

**Comment by lucadelu** [comment]
I like the idea, the only problem if virtual file system are supported by default from all distributions/operative systems

**Review by ninsbl — APPROVED** [review]
Looks good to me.
I tested on Windwos (OSGeo4W) to try another OS for virtual file systems and it works fine there.

**Comment by veroandreo** [comment]
Thanks @lucadelu and @ninsbl!

@nilason would you kindly test this PR in Mac, please?

**Comment by nilason** [comment]
> @nilason would you kindly test this PR in Mac, please?

This is a bit of new ground for me, so please do have some patience with me :) . I'll give it a try.

**Comment by nilason** [comment]
Turned out (as I suspected) testing this wasn't without difficulties. Too many bumps in the road for me to iron out now. I need to develop/learn a workflow for add-on dev and testing.
I intend to test this either as PR or merged, but you need not to wait for me.

**Comment by ninsbl** [comment]
> Too many bumps in the road for me to iron out now. I need to develop/learn a workflow for add-on dev and testing.

@nilason With a version of GRASS GIS 7.9 that includes this:
https://github.com/OSGeo/grass/pull/1177
You may test addons by installing them with g.extension:
`g.extension url="https://github.com/veroandreo/grass-addons" branch="fix-landsat-import" extension="i.landsat.import"`
Then you can run either sample code (from i.landsat.download + i.landsat.import)...

That should be sufficient in this case...

**Comment by nilason** [comment]
> > Too many bumps in the road for me to iron out now. I need to develop/learn a workflow for add-on dev and testing.
> 
> @nilason With a version of GRASS GIS 7.9 that includes this:
> [OSGeo/grass#1177](https://github.com/OSGeo/grass/pull/1177)
> You may test addons by installing them with g.extension:
> `g.extension url="https://github.com/veroandreo/grass-addons" branch="fix-landsat-import" extension="i.landsat"`
> Then you can run either sample code (from i.landsat.download + i.landsat.import)...
> 
> That should be sufficient in this case...

Thanks! I'll give it a go.
Just quick questions: is svn (still) required for g.extension and why isn't `i.landsat` (or i.landsat.import or i.landsat.download) listed with `g.extension -l`.

**Comment by nilason** [comment]
With 7.8.5 I get:
```
g.extension url="https://github.com/veroandreo/grass-addons" branch="fix-landsat-import" extension="i.landsat" 
Fetching <i.landsat> from
<https://github.com/veroandreo/grass-addons/archive/fix-landsat-import.zip>
(be patient)...
Compiling...
make: *** No targets specified and no makefile found.  Stop.
ERROR: Compilation failed, sorry. Please check above error messages.

```

**Comment by ninsbl** [comment]
> Just quick questions: is svn (still) required for g.extension and why isn't `i.landsat` (or i.landsat.import or i.landsat.download) listed with `g.extension -l`.

Unfortunately, yes. See related discussion here: https://github.com/OSGeo/grass/issues/625
Please add a comment there if you have any regarding the possible solution to remove svn (and maybe even git) as a dependency.

**Comment by veroandreo** [comment]
Is issue https://github.com/OSGeo/grass-addons/issues/397 related to `g.extenson -l` not showing metadata for i.landsat? Seems to happen for other modules too

**Comment by veroandreo** [comment]
> With 7.8.5 I get:
> 
> ```
> g.extension url="https://github.com/veroandreo/grass-addons" branch="fix-landsat-import" extension="i.landsat" 
> Fetching <i.landsat> from
> <https://github.com/veroandreo/grass-addons/archive/fix-landsat-import.zip>
> (be patient)...
> Compiling...
> make: *** No targets specified and no makefile found.  Stop.
> ERROR: Compilation failed, sorry. Please check above error messages.
> ```

I get the same... both with grass-dev and 7.8.5. Is this related to i.landsat or g.extension?

**Comment by veroandreo** [comment]
I will merge this so it can be tested more easily in Mac too. In case it does not work, we can adapt or revert.

**Pull request merged**
