### PR TITLE
tools/cronjobs_osgeo_lxd: fix Add-On src and commits url in the manual html page

### PR DESCRIPTION
**Pull request by tmszi**
Allow build Add-Ons with correct src and commits url in the manual page with build script.

Apply first this [PR,](https://github.com/OSGeo/grass/pull/1009) please.

### CODE REVIEW

**Comment by neteler** [comment]
Thanks, I have patched the repos on the server and recompiled the manual pages with the script.

It has been applied since I get with the previous call

```
neteler@grasslxd:~$ sh ~/cronjobs/compile_addons_git.sh ~/src/grass-addons/grass7/ ~/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/ ~/.grass7/addons
Set GRASS startup program arg parameter path
```

(so that should be fine).

Still... (random addon):
https://grass.osgeo.org/grass78/manuals/addons/i.sentinel.mask.html

it doesn't point to the history (or I am missing some patch on the server).

**Comment by neteler** [comment]
BTW, the `build.log` is here: https://grass.osgeo.org/grass78/binary/linux/snapshot/

**Comment by tmszi** [comment]
> Thanks, I have patched the repos on the server and recompiled the manual pages with the script.
> 
> It has been applied since I get with the previous call
> 
> ```
> neteler@grasslxd:~$ sh ~/cronjobs/compile_addons_git.sh ~/src/grass-addons/grass7/ ~/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/ ~/.grass7/addons
> Set GRASS startup program arg parameter path
> ```
> 
> (so that should be fine).
> 
> Still... (random addon):
> https://grass.osgeo.org/grass78/manuals/addons/i.sentinel.mask.html
> 
> it doesn't point to the history (or I am missing some patch on the server).

Maybe you miss apply this [PR](https://github.com/OSGeo/grass/pull/1009) on releasebranch_7_8 ? 

This command is important in [build script](https://github.com/OSGeo/grass-addons/pull/307/commits/8a0844b9ef47bcdb71f36221a1647c709b39fa91#diff-26fec5cb1bc02e1a45f9839f31067986R111), and '-p' flag added in this [PR](https://github.com/OSGeo/grass/pull/1009).  In build script `g.extension -p` download  'addons_paths.json' file, and than mkhtml script work correctly (set correct src / commit url in the htm manual page).
```
/usr/bin/grass78 --tmp-location EPSG:4326 --exec g.extension -p

Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Cleaning up temporary files...
Executing <g.extension -p> ...
Add-Ons json file paths: /home/tomas/.grass7/addons/addons_paths.json
Execution of <g.extension -p> finished.
Cleaning up temporary files...
```

**Comment by tmszi** [comment]
> Thanks, I have patched the repos on the server and recompiled the manual pages with the script.
> 
> It has been applied since I get with the previous call
> 
> ```
> neteler@grasslxd:~$ sh ~/cronjobs/compile_addons_git.sh ~/src/grass-addons/grass7/ ~/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/ ~/.grass7/addons
> Set GRASS startup program arg parameter path
> ```

My mistake, I changed the [order of the script parameters in the condition](https://github.com/OSGeo/grass-addons/pull/307/commits/499db12a25e308f79a2e0c4ffb085d4418ef7921#diff-26fec5cb1bc02e1a45f9839f31067986R30). I fixed it in [499db12](https://github.com/OSGeo/grass-addons/pull/307/commits/499db12a25e308f79a2e0c4ffb085d4418ef7921).

```
sh /tmp/src/compile_addons_git.sh /tmp/grass-addons/grass7/ /tmp/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/ /tmp/.grass7/addons /tmp/src/releasebranch_7_8/bin.x86_64-pc-linux-gnu/grass78

-----------------------------------------------------
Addons '/tmp/.grass7/addons'...
-----------------------------------------------------
Compiling db.join... SUCCESS
Compiling d.explanation.plot... SUCCESS
Compiling d.frame... SUCCESS
Compiling d.mon2... SUCCESS
Compiling d.vect.colbp... SUCCESS
Compiling d.vect.colhist... SUCCESS
Compiling d.vect.thematic2... SUCCESS
Compiling g.citation... SUCCESS
Compiling g.cloud... SUCCESS
Compiling g.compare.md5... SUCCESS
Compiling g.copyall... SUCCESS
Compiling g.download.location... SUCCESS
Compiling g.isis3mt... FAILED
Compiling g.proj.all... SUCCESS
Compiling g.proj.identify... SUCCESS
Compiling g.rename.many... SUCCESS
....

tail -n 20 /tmp/.grass7/addons/docs/html/i.sentinel.mask.html

--><h2>SOURCE CODE</h2>
<p>Available at: <a href="https://github.com/OSGeo/grass-addons/tree/master/grass7/imagery/i.sentinel/i.sentinel.mask">i.sentinel.mask source code</a> (<a href="https://github.com/OSGeo/grass-addons/commits/master/grass7/imagery/i.sentinel/i.sentinel.mask">history</a>)</p>
<hr class="header">
<p>
<a href="index.html">Main index</a> |
<a href="imagery.html">Imagery index</a> |
<a href="topics.html">Topics index</a> |
<a href="keywords.html">Keywords index</a> |
<a href="graphical_index.html">Graphical index</a> |
<a href="full_index.html">Full index</a>
</p>
<p>
&copy; 2003-2020
<a href="http://grass.osgeo.org">GRASS Development Team</a>,
GRASS GIS 7.8.5dev Reference Manual
</p>

</div>
</body>
</html>
```

**Comment by neteler** [comment]
Yes, success! 
e.g. https://grass.osgeo.org/grass78/manuals/addons/i.sentinel.mask.html

**Comment by tmszi** [comment]
In the [b470080](https://github.com/OSGeo/grass-addons/pull/307/commits/b470080141e52b89484e6916bc0e576e3df12b62) I added [checking Add-On source and commits URL existence](https://github.com/OSGeo/grass-addons/pull/307/commits/b470080141e52b89484e6916bc0e576e3df12b62#diff-26fec5cb1bc02e1a45f9839f31067986R149) in the html manual page with logging into stdout, log file and html page.

**Stdout / log file:**

```
Checking db.csw.admin.html... source and commits URL: CORRECT
Checking db.csw.harvest.html... source and commits URL: CORRECT
Checking db.csw.run.html... source and commits URL: CORRECT
Checking db.join.html... source and commits URL: CORRECT
Checking d.explanation.plot.html... source and commits URL: CORRECT
Checking d.frame.html... source and commits URL: CORRECT
Checking d.mon2.html... source and commits URL: CORRECT
Checking d.vect.colbp.html... source and commits URL: CORRECT
Checking d.vect.colhist.html... source and commits URL: CORRECT
Checking d.vect.thematic2.html... source and commits URL: CORRECT
Checking g.citation.html... source and commits URL: CORRECT
Checking g.cloud.html... source and commits URL: CORRECT
Checking g.compare.md5.html... source and commits URL: CORRECT
Checking g.copyall.html... source and commits URL: CORRECT
Checking g.download.location.html... source and commits URL: CORRECT
Checking g.gui.cswbrowser.html... source and commits URL: CORRECT
Checking g.gui.metadata.html... source and commits URL: CORRECT
Checking g.gui.mwprecip.html... source or commits URL: INCORRECT
Checking g.proj.all.html... source and commits URL: CORRECT
Checking g.proj.identify.html... source and commits URL: CORRECT
Checking g.rename.many.html... source and commits URL: CORRECT
Checking i.ann.maskrcnn.html... source and commits URL: CORRECT
Checking i.ann.maskrcnn.train.html... source and commits URL: CORRECT
Checking i.cutlines.html... source and commits URL: CORRECT
Checking i.cva.html... source and commits URL: CORRECT
...
```

**Html page:**

check_addons_src_commits_url_html_log

According test only wx.mwprecip Add-On (g.gui.mwprecip.html) html manual page doesn't contain source and commits URL.

```
 tail -n 20 /tmp/.grass7/addons/docs/html/g.gui.mwprecip.html

<h2>SOURCE CODE</h2>
<p>Available at: <a href="">g.gui.mwprecip source code</a> (<a href="">history</a>)</p>
<hr class="header">
<p>
<a href="index.html">Main index</a> |
<a href="general.html">General index</a> |
<a href="topics.html">Topics index</a> |
<a href="keywords.html">Keywords index</a> |
<a href="graphical_index.html">Graphical index</a> |
<a href="full_index.html">Full index</a>
</p>
<p>
&copy; 2003-2020
<a href="http://grass.osgeo.org">GRASS Development Team</a>,
GRASS GIS 7.8.5dev Reference Manual
</p>

</div>
</body>
</html>
```

**Review by neteler — APPROVED** [review]
Thanks for your efforts, I'd suggest to merge

**Comment by tmszi** [comment]
In the [c5aca07](https://github.com/OSGeo/grass-addons/pull/307/commits/c5aca07716dc5ef497e4e3e187e69f347e0b4d7e) replace call `g.extension -p` with correct flag `g.extension -j`.

**Comment by neteler** [comment]
Since https://github.com/OSGeo/grass/pull/1009 has been merged, I suggest to also merge this PR and then watch the next builds of online manuals :-)

**Comment by neteler** [comment]
I think it works now (just triggered the cronjob manually). Random module:

https://grass.osgeo.org/grass7/manuals/addons/i.nightlights.intercalibration.html

... looks fine I think.

Still I saw this (no idea why) error:

`Syntax error: redirection unexpected`

The log on cmd line:

```
...
Compiling v.surf.tps... SUCCESS
Compiling v.tin.to.rast... SUCCESS
Compiling v.transects... SUCCESS
Compiling v.vol.idw... SUCCESS
Compiling v.what.rast.multi... SUCCESS
Compiling v.what.spoly... SUCCESS
Compiling v.what.strds.timestamp... SUCCESS

/home/neteler/cronjobs/check_addons_urls.sh: 30: /home/neteler/cronjobs/check_addons_urls.sh: Syntax error: redirection unexpected

Log file written to </home/neteler/.grass7/addons/logs/>
Makefile:13: warning: overriding recipe for target '/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/etc/d.polar'
../../include/Make/ScriptRules.make:19: warning: ignoring old recipe for target '/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/etc/d.polar'
Makefile:16: warning: overriding recipe for target '/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/etc/db.test'
../../include/Make/ScriptRules.make:19: warning: ignoring old recipe for target '/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/etc/db.test'
Finished GRASS 78 x86_64-pc-linux-gnu compilation.
Written to: /var/www/code_and_data//grass78/binary/linux/snapshot
Copied HTML manual to https://grass.osgeo.org/grass78/manuals/
Copied pygrass progman to https://grass.osgeo.org/grass78/manuals/libpython/
neteler@grasslxd:~$ l /home/neteler/cronjobs/check_addons_urls.sh
lrwxrwxrwx 1 neteler users 76 Oct 16 17:15 /home/neteler/cronjobs/check_addons_urls.sh -> /home/neteler/src/grass-addons/tools/cronjobs_osgeo_lxd/check_addons_urls.sh*

```

**Comment by neteler** [comment]
ok I guess I know... it's Debian:
```

neteler@grasslxd:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)

neteler@grasslxd:~$ ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Jan 17  2019 /bin/sh -> dash*
```

We will need to explicitly request `/bin/bash` in the shebang.

**Comment by tmszi** [comment]
Problematic is this [line](https://github.com/OSGeo/grass-addons/blob/master/tools/cronjobs_osgeo_lxd/check_addons_urls.sh#L30) (redirection). Dash doesn't have the `<<<` redirection operator.

`read -a template_page_url <<< "${urls[$i]}"`

**Comment by tmszi** [comment]
> We will need to explicitly request `/bin/bash` in the shebang.

I've already fixed it.

**Comment by neteler** [comment]
I've overlooked that besides 3000fb037a0cc8f85bae61de2a6ba8a827d19678 also 20a434263186244907e88b2073457ac3cc486c73 is needed as it takes precedence over the shebang.
Now the redirection issue is solved.

**Pull request merged**
