### PR TITLE
addons scripts: define versions as variables on top

### PR DESCRIPTION
**Pull request by neteler**
Avoid hardcoded version numbers throughout the script and use variables defined on top.

TODO: update `utils/addons/build-xml.py`

### CODE REVIEW

**Comment by neteler** [comment]
@tmszi may I merge this PR?

**Comment by tmszi** [comment]
> @tmszi may I merge this PR?

Are these scripts running at CTU server? Wouldn't it be better to use only the ones we have in the osgeo lxd server container? I thought these were no longer necessary, if so I would need more time for a review/test.

**Comment by neteler** [comment]
> > @tmszi may I merge this PR?
> 
> Are these scripts running at CTU server?

I have no idea... I thought we use them as well.

> Wouldn't it be better to use only the ones we have in the osgeo lxd server container?

Definitely!

> I thought these were no longer necessary, if so I would need more time for a review/test.

Ok, can we delete the entire directory https://github.com/OSGeo/grass-addons/blob/grass8/utils/addons/ ?

**Comment by tmszi** [comment]
> Ok, can we delete the entire directory https://github.com/OSGeo/grass-addons/blob/grass8/utils/addons/ ?

We don't use them, we can delete them. Yes I agree.

**Pull request closed without merging**
