### PR TITLE
Fix python3 warnings and errors in v.surf.icw

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Review by lucadelu — APPROVED** [review]

**Comment by neteler** [comment]
@smathermather once you believe it is ready to be merged pls change this PR from draft to merge-able state

**Comment by lucadelu** [comment]
sorry I didn't check the discussion in the issue, removing approval

**Comment by smathermather** [comment]
Per dialog at https://github.com/OSGeo/grass-addons/issues/354, I am closing this pull request.

**Comment by smathermather** [comment]
Ok, this is ready for review. I ran it through `futurize`, and it runs fine in Python3. I don't have a dev environment suitable for testing this in python2, but I consider this ready for review.

**Comment by smathermather** [comment]
It's super nice to have this tool:
image

**Comment by neteler** [comment]
Thanks for your contribution (and the screenshot is amazing!)

**Comment by smathermather** [comment]
Yay! My pleasure and thanks!

**Comment by smathermather** [comment]
This is a super cool tool. I haven't been this excited since ArcView 3.1:
image

**Comment by neteler** [comment]
Please consider to donate a screenshot to our https://grass.osgeo.org/learn/gallery/ ;-)

(best done at https://github.com/OSGeo/grass-website along with a one-liner)

**Comment by smathermather** [comment]
Completed. Thanks for the tip! https://github.com/OSGeo/grass-website/pull/231

**Pull request merged**
