### PR TITLE
[Bug] Fix or replace i.pr Perl scripts which fail with perlcritic 

### LINKED ISSUE #619: [Bug] Fix or replace i.pr Perl scripts which fail with perlcritic
**Name of the addon**

i.pr

**Describe the bug**

Perl scripts for _i.pr_ in `src/imagery/i.pr/PRLIB/` trigger warnings from the _perl_ linter in Super-Linter. 

**To Reproduce**

Run perlcritique or perl linter from Super-Linter.

```sh
perlcritic .
```

**Expected behavior**

No linter issues from the code and enabled Perl checks in Super-Linter. 

**Screenshots**

perlcritic:

```
src/imagery/i.pr/PRLIB/extract_functions.pl: "require" statement with library name as string at line 3, column 1.  Use a bareword instead.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_functions.pl: Code before strictures are enabled at line 5, column 1.  See page 429 of PBP.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_functions.pl: Bareword file handle opened at line 23, column 6.  See pages 202,204 of PBP.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_functions.pl: Two-argument "open" used at line 23, column 6.  See page 207 of PBP.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_functions.pl: Bareword file handle opened at line 101, column 6.  See pages 202,204 of PBP.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_functions.pl: Two-argument "open" used at line 101, column 6.  See page 207 of PBP.  (Severity: 5)
src/imagery/i.pr/PRLIB/extract_ps.pl: Code before strictures are enabled at line 3, column 1.  See page 429 of PBP.  (Severity: 5)
```

Super-Linter GitHub Action:

```
2021-10-02T07:49:28.2420328Z File:[./src/imagery/i.pr/PRLIB/extract_functions.pl]
2021-10-02T07:49:28.2449902Z ERROR! Found errors in [perl] linter!
2021-10-02T07:49:28.2450831Z ERROR:[Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 9.
2021-10-02T07:49:28.2452068Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 11.
2021-10-02T07:49:28.2453307Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 11.
2021-10-02T07:49:28.2454512Z Global symbol "$done" requires explicit package name (did you forget to declare "my $done"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 12.
2021-10-02T07:49:28.2455706Z Global symbol "$opt_f" requires explicit package name (did you forget to declare "my $opt_f"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 14.
2021-10-02T07:49:28.2457183Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 15.
2021-10-02T07:49:28.2460711Z Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 16.
2021-10-02T07:49:28.2461971Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 16.
2021-10-02T07:49:28.2463252Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 16.
2021-10-02T07:49:28.2464451Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 16.
2021-10-02T07:49:28.2465715Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 17.
2021-10-02T07:49:28.2467017Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 17.
2021-10-02T07:49:28.2468245Z Global symbol "$done" requires explicit package name (did you forget to declare "my $done"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 18.
2021-10-02T07:49:28.2469440Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 19.
2021-10-02T07:49:28.2470666Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_functions.pl line 19.
2021-10-02T07:49:28.2471666Z ./src/imagery/i.pr/PRLIB/extract_functions.pl had compilation errors.]
2021-10-02T07:49:28.2472594Z ---------------------------
2021-10-02T07:49:28.2473091Z File:[./src/imagery/i.pr/PRLIB/extract_ps.pl]
2021-10-02T07:49:28.2492165Z ERROR! Found errors in [perl] linter!
2021-10-02T07:49:28.2493045Z ERROR:[Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 4.
2021-10-02T07:49:28.2494222Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 6.
2021-10-02T07:49:28.2495347Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 6.
2021-10-02T07:49:28.2496737Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 9.
2021-10-02T07:49:28.2497868Z Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 10.
2021-10-02T07:49:28.2499038Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 10.
2021-10-02T07:49:28.2500225Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 10.
2021-10-02T07:49:28.2501351Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 10.
2021-10-02T07:49:28.2503175Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 11.
2021-10-02T07:49:28.2504888Z Global symbol "$extension" requires explicit package name (did you forget to declare "my $extension"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 11.
2021-10-02T07:49:28.2506189Z Global symbol "$out" requires explicit package name (did you forget to declare "my $out"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 12.
2021-10-02T07:49:28.2507304Z Global symbol "$name" requires explicit package name (did you forget to declare "my $name"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 12.
2021-10-02T07:49:28.2508426Z Global symbol "@files" requires explicit package name (did you forget to declare "my @files"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 13.
2021-10-02T07:49:28.2509555Z Global symbol "$nfiles" requires explicit package name (did you forget to declare "my $nfiles"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 13.
2021-10-02T07:49:28.2510689Z Global symbol "$out" requires explicit package name (did you forget to declare "my $out"?) at ./src/imagery/i.pr/PRLIB/extract_ps.pl line 13.
2021-10-02T07:49:28.2511601Z ./src/imagery/i.pr/PRLIB/extract_ps.pl had compilation errors.]
```

**Additional context**

Super-Linter checks for Perl need to be disabled now.

This can be fixed by rewriting the script in Python.

### PR DESCRIPTION
**Pull request by AnuRage-git**
The mentioned issues with super-linter concerning the mentioned Perl scripts have been resolved to the best of my knowledge. Kindly review the changes and notify me if any more changes need to be made.

### CODE REVIEW

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
The `extract_functions.pl` should be in `src/imagery/i.pr/PRLIB/extract_functions.pl`. I think you just added a new file to the top directory instead of replacing the broken file.

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
Looks good...just remove that other file.

Also, if at all possible, can you please post your runs of perlcritic or whatever you are running?

**Comment by AnuRage-git** [comment]
@wenzeslaus The requested changes have been made. The file from the parent directory has been removed and changes to the original file have been made.
I used perlCritic on http://perlcritic.com/ as I didn't know if the AUR package perl-perl-critic on my system would be updated to the latest standards. The severity level I tried to match by reading the logs of the raised issue.
I have provided the screenshots below

For extract_functions.pl :
Screenshot_20240104_110938

For extract_ps.pl :
Screenshot_20240104_111019

**Comment by neteler** [comment]
Why did you close this PR, @AnuRage-git ?

**Comment by AnuRage-git** [comment]
Sorry for that. It had been quite a long time since I posted the changes and there weren't any replies. I'm still new to GitHub and open source contributions, I've only been using Linux for so long, never really got around to contributing. So I didn't know what to do from there. I do apologise for that mistake.

**Comment by neteler** [comment]
All good. We are just a group of volunteers - so we are not answer immediately :-)
The last reply was two days ago, so that should be fine...

**Comment by AnuRage-git** [comment]
Yes, Thank you. Also I looked at the OSGeo project. I would like to further contribute to this with both fixes and adding more features and support for my own learnings and also for the project. It would be really helpful if you could tell me where to start

**Review by wenzeslaus — APPROVED** [review]

**Comment by wenzeslaus** [comment]
Approved and merged. Thank you. And yes, please give me more time to respond unless you have a prior agreement with me. ;-) As Markus says, many of these reviews happen on limited volunteered employee/employer time or straight free time, so while a quick turnaround is certainly possible in general, without a prior agreement, please be flexible with the turnaround time.

> ...I would like to further contribute to this with both fixes and adding more features and support for my own learnings and also for the project.

That's great to hear. I hope the delay didn't discouraged you much.

> It would be really helpful if you could tell me where to start

There is a list of ["good first issues"](https://github.com/OSGeo/grass/labels/good%20first%20issue) aimed at beginners in the OSGeo/grass repo. This (OSGeo/grass-addons) repo has some code quality issues just like the Perlcritic ones but for Python, so it depends if Python is something you want to do. There is plenty geospatial user-centered topics if you come as a current user, two prominent categories are missing examples and images in the documentation (requires command line and very basic HTML editing) and broken tests (tests are in Python, some in Bash).

As a Linux user, you already have plenty of knowledge which allows you to effectively contribute to GRASS GIS, so it just depends on what exactly you want to do and whether or how much you used GRASS GIS as a user (through an UI or API).

**Pull request merged**
