### PR TITLE
cronjobs: inject canonical URLs into older manual pages (SEO)

### LINKED ISSUE #4579: [Bug] docs: Fix search engine ranking of manual pages (SEO)
## Describe the bug

The GRASS GIS manual pages of the different versions have been published for a long time with a difficult to understand concept of being invisible, redirected or shown, which also strongly affects the search engine ranking.

Note: issue posted here since the core manual pages are affected (while the [cronjobs](https://github.com/OSGeo/grass-addons/tree/grass8/utils/cronjobs_osgeo_lxd/) are maintained in the addon repository).

## How Python publishes its man pages

The scope of of a pull request in preparation is to partially adopt the Python manual pages concept which looks like this (checked Oct 23, 2024):

- Python 3.14 (in development): https://docs.python.org/3.14/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.13 (stable): https://docs.python.org/3.13/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.12 (stable): https://docs.python.org/3.12/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.11 (security-fixes): https://docs.python.org/3.11/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.10 (security-fixes): https://docs.python.org/3.10/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.9 (security-fixes): https://docs.python.org/3.9/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- Python 3.8 (EOL): https://docs.python.org/3.8/ -> `<link rel="canonical" href="https://docs.python.org/3/index.html" />`
- ...

A [Google search for "Python documentation"](https://www.google.com/search?client=firefox-b-d&q=Python+documentation) returns as the first hit the "3.13.0 Documentation" with the URL https://docs.python.org/. Clicking on this takes the user to https://docs.python.org/3/, which is identical to https://docs.python.org/3.13/.

This means that the same documentation is served at two URLs:

- https://docs.python.org/3/ - the canonical URL
- https://docs.python.org/3.13/ - the current stable one

## How can GRASS GIS publish its manual pages?

While the situation in the GRASS GIS project is a bit different, we can mimic the Python approach to some extent.

**Current GRASS GIS version overview**

| **label**      |  Ver   |
| -------------- | ------ |
| legacy         |  7.8   |
| old            |  8.3   |
| current stable |  8.4   |
| preview        |  8.5   |

I have started to locally implement modifications in the cronjobs to improve the terrible SEO situation and make more versions properly visible (ovedue for a long time).

Now, for a few days we have the following approach deployed on the server for testing purposes (cronjob PR coming soon):

- https://grass.osgeo.org/grass-devel/manuals/ - now copied in modified cronjob from 8.5.x (i.e., `main` branch) with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">`
- https://grass.osgeo.org/grass-stable/manuals/ - now copied in modified cronjob from 8.4.x (i.e., `releasebranch_8_4` branch) - **this is the overall main manual**
- https://grass.osgeo.org/grass85/manuals/ - current unreleased development (generated by cronjob, then copied to grass-devel) - with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">`
- https://grass.osgeo.org/grass84/manuals/ - current stable release branch (generated by cronjob, then copied to grass-stable) - with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">`
- https://grass.osgeo.org/grass78/manuals/ - with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">` and red box pointing to to grass-stable (generated by cronjob with box URL and canonical version defined) 
- https://grass.osgeo.org/grass65/manuals/ - with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">` and red box pointing to to grass-stable (old static pages)
- https://grass.osgeo.org/grass64/manuals/ - with `<link rel="canonical" href="https://grass.osgeo.org/grass-stable/manuals/index.html">` and red box pointing to to grass-stable (old static pages)
- ... likewise other old manual versions.

Sitemaps:
- These have also been updated, this is done by the  [cronjobs](https://github.com/OSGeo/grass-addons/tree/grass8/utils/cronjobs_osgeo_lxd/).

**Observations:**

- **SEO**: Without indication of "**canonical**" URLs different versions wipe each out out in search engines. Canonical tags help consolidate duplicate or similar content by specifying the preferred version of a page, ensuring search engines index and rank the desired URL while avoiding duplicate content issues. All older and "devel" manual pages now point to "stable" as the canonical to avoid duplicate content.
- **Very old versions**: The static 6.4 and 6.5 versions have recently been reactivated and the associated Apache redirects on grass.osgeo.org removed to reduce the current SEO problems. So they are accessible again, but will not be indexed by search engines due to the "canonical" pointers (see above). Note that e.g. older scientific publications point to these (now) old GRASS GIS manual pages.
- **Rolling stable manual pages**: As I don't see any point in releasing the static released stable version (e.g. 8.4.0), instead the  daily stable release branch is used to make manual improvements immediately available.
- **"Devel" vs "Preview"**: Historically, we have called the development version "grass-devel", which is called "preview" on the website. This should be streamlined.

Note that it may even take weeks for Google etc. to "learn" the improved structure. At time, I am feeding [Google search tools](https://search.google.com/search-console?hl=en&resource_id=https://grass.osgeo.org/) and [Bing webmasters tools](https://www.bing.com/webmasters/tools/) with the appropriate updates every few days.

## Additional context

**TODO**:
- https://github.com/OSGeo/grass-addons/pull/1215 needs to be merged first to disentangle the tasks
- create new pull request with aforementioned changes (TODO MN)
- monitor  [Google search tools](https://search.google.com/search-console?hl=en&resource_id=https://grass.osgeo.org/) and [Bing webmasters tools](https://www.bing.com/webmasters/tools/)  about the changes with special focus on "Page indexing > Alternate page with proper canonical tag" (TODO MN)
- Sitemap update: https://grass.osgeo.org/sitemap.xml to grass-stable/grass-devel: https://github.com/OSGeo/grass-website/pull/482

### PR DESCRIPTION
**Pull request by neteler**
The GRASS GIS manual pages of the different versions have been published for a long time with a difficult to understand concept of being invisible, redirected or shown, which also strongly affects the search engine ranking.

SEO: Without indication of "canonical" URLs different versions wipe each out out in search engines. Canonical tags help consolidate duplicate or similar content by specifying the preferred version of a page, ensuring search engines index and rank the desired URL while avoiding duplicate content issues.

This PR changes the cronjob scripts to
- inject "grass-stable" as the "canonical" into older manual pages under versioned URL
- inject "grass-devel" as the "canonical" into the development manual pages under versioned URL

Like this no "duplicate content" from a SEO perspective should occur.

Also [robots.txt](https://grass.osgeo.org/robots.txt) is updated to reactivate the manual pages of old GRASS GIS versions (which now contain "grass-stable" as the canonical).

Additionally, rewrite red box injection to avoid globbing error `argument list too long` old versions of libpython manual.

Fixes https://github.com/OSGeo/grass/issues/4579

### CODE REVIEW

**Comment by neteler** [comment]
Note: these files are now deployed on grass.osgeo.org for testing.

**Comment by echoix** [comment]
Wouldn't the grass-devel and grass-stable primary content be rather similar, thus being potentially penalized as duplicates?

How does this method handle pages that don't exist in later versions, or are renamed/moved?
It doesn't happen often, but we had some every now and then.

**Comment by neteler** [comment]
> Wouldn't the grass-devel and grass-stable primary content be rather similar, thus being potentially penalized as duplicates?

Very good point.
I have changed it in 9824486c18585376f0d734a778689fbf3850aa55 to inject in the 8.5 versioned and the "grass-devel" manual sections the "canonical" to point to "stable" rather than to "devel".

Deployed update on grass.osgeo.org, triggered cronjob and told Google Search about it.

> How does this method handle pages that don't exist in later versions, or are renamed/moved? It doesn't happen often, but we had some every now and then.

A few of them are handled with redirects in Apache. I would not know any other method.

**Comment by neteler** [comment]
Too bad, now the building with `cron_grass_preview_build_binaries.sh` on the Debian grass.osgeo.org server is broken after the MD merge:

```
...
Parsing <v.what.strds.timestamp>... SUCCESS
Parsing <wx.metadata>... FAILED
Parsing <wx.mwprecip>... FAILED
Parsing <wx.stream>... FAILED
Parsing <wx.wms>... FAILED
+ cp /home/neteler/.grass8/addons/modules.xml /var/www/code_and_data/addons/grass8/modules.xml
+ export ARCH
+ export ARCH_DISTDIR=/home/neteler/src//main/dist.x86_64-pc-linux-gnu
+ export GISBASE=/home/neteler/src//main/dist.x86_64-pc-linux-gnu
+ export VERSION_NUMBER=8.5
+ python3 /home/neteler/src//main/man/build_keywords.py /var/www/code_and_data/grass85/manuals/ /var/www/code_and_data/grass85/manuals/addons/
Traceback (most recent call last):
  File "/home/neteler/src//main/man/build_keywords.py", line 202, in <module>
    build_keywords("md")
  File "/home/neteler/src//main/man/build_keywords.py", line 68, in build_keywords
    from build_md import (
  File "/home/neteler/src/main/man/build_md.py", line 264, in <module>
    man_dir = os.path.join(os.environ["MDDIR"], "source")
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MDDIR'
```

Can @landam help?

**Comment by neteler** [comment]
> Too bad, now the building with `cron_grass_preview_build_binaries.sh` on the Debian grass.osgeo.org server is broken after the MD merge:

Bugfix PR: https://github.com/OSGeo/grass/pull/4739

**Comment by echoix** [comment]
Is everything clear for this one now?

**Comment by neteler** [comment]
To see, if the jobs are still successful, see

- https://grass.osgeo.org/grass78/binary/linux/snapshot/build.log.txt
- https://grass.osgeo.org/grass83/binary/linux/snapshot/build.log.txt
- https://grass.osgeo.org/grass84/binary/linux/snapshot/build.log.txt
- https://grass.osgeo.org/grass85/binary/linux/snapshot/build.log.txt

(currently: running successfully)

**Comment by neteler** [comment]
> Is everything clear for this one now?

Almost. I am at time fixing the red box injection into the old libpython manual pages which fails with the globbing related error `argument list too long` due to recursive `find` operations.
I am currently testing a different approach on the server.

**Comment by neteler** [comment]
@wenzeslaus from my side this PR is now complete.

**Comment by neteler** [comment]
cronjob files including `cron_job_list_grass` updated and deployed on server.

**Pull request merged**
