### PR TITLE
i.ann.maskrcnn.detect: fix problems with matplotlib on Windows

### PR DESCRIPTION
**Pull request by pesekon2**

### CODE REVIEW

**Review by hellik — COMMENTED** [review]
no chance to test it here, though it looks ok so far.

see https://matplotlib.org/3.3.2/tutorials/introductory/usage.html for the different backend engines.

when I fixed r.width.funct.py back then, wxagg was the best backend to work in all os.

_WXAgg | Agg rendering to to a wxWidgets canvas (requires wxPython)_

as we use wxpython for GUI, it should be safe.

**Review by ninsbl — APPROVED** [review]
Looks good to me.

While you are at it, and if you don`t mind, it would be great if you could also fix also:
https://github.com/OSGeo/grass-addons/blob/03a2b1e6a1d4d30fb974910db9958992c82da504/grass7/imagery/i.variance/i.variance.py#L110
https://github.com/OSGeo/grass-addons/blob/98ca4366a03193e998c467c55fb095ade9d8b426/grass7/vector/v.class.ml/ml_functions.py#L15
https://github.com/OSGeo/grass-addons/blob/98ca4366a03193e998c467c55fb095ade9d8b426/grass7/vector/v.class.ml/features.py#L6
https://github.com/OSGeo/grass-addons/blob/98ca4366a03193e998c467c55fb095ade9d8b426/grass7/raster/r.colors.cubehelix/r.colors.cubehelix.py#L212
https://github.com/OSGeo/grass-addons/blob/f82e2ceaa9ca38be5c66ae5f0234d3f46350eed6/grass7/vector/v.stream.profiler/v.stream.profiler.py#L159
the same way.

Otherwise I could open a new PR...

**Comment by ninsbl** [comment]
Great. Thanks. Maybe @landam  could have a look if that is OK to merge?

**Comment by neteler** [comment]
I take liberty to merge...

**Pull request merged**
