### PR TITLE
Python 3: xrange compatibility fix

### PR DESCRIPTION
**Pull request by neteler**
With this change both Python 2's `xrange()` and Python 3's `range()` are accommodated.

### CODE REVIEW

**Comment by neteler** [comment]
Merging now (it follows ad1af93ddd968cf42328cc493cacbbe60d2e3ee5 and 62d7c2f9eada1e56af90c409870fdde62311d40a)

**Comment by ecodiv** [comment]
@neteler thanks. I hadn't seen the review request earlier (not really got the hang of how things work on Github yet). I was actually wondering if xrange() could simply be replaced by range(). So it is better to use your solution I guess?

**Comment by neteler** [comment]
Like this it should work for both Py2 and Py3.

**Comment by petrasovaa** [comment]
Just to clarify, in most cases it's safe to just replace it. Python 2 xrange is pretty much the same as Python 3 range (with some differences). Without looking at each individual case, this is a safe way to do it.

**Pull request merged**
