### PR TITLE
addons: remove deprecated addons

### PR DESCRIPTION
**Pull request by neteler**
- cleanup of long time unused code (reduces confusion and wrong "failed" entries in addon log files)

### CODE REVIEW

**Comment by neteler** [comment]
Outdated and removable:
- raster/r.in.arc: replaced by `r.in.gdal`/`r.import`
- raster/r.lfp: replaced by `r.accumulate`
- raster/r.los: replaced by `r.viewshed`
- raster/r.modis: renamed to `i.modis`
- raster/r.out.arc: : replaced by `r.out.gdal`
- raster/r.out.tiff: : replaced by `r.out.gdal`
- raster/r.sentinel: renamed to `i.sentinel`

Moved to GRASS-core:
- imagery/i.fusion.brovey: replaced with `i.pansharpen`
- raster/r.fill.gaps: ported to core as `r.fill.stats`
- raster/r.geomorphon
- raster/r.grow.shrink: continued as `r.grow.distance` and its Python `r.grow` wrapper
- vector/v.clip
- vector/v.profile

**Review by petrasovaa — APPROVED** [review]

**Review by HuidaeCho — APPROVED** [review]

**Review by wenzeslaus — COMMENTED** [review]
I have used *r.out.tiff* at one point because it handled color table differently than *r.out.gdal*. I think the colors in the TIFF from *r.out.tiff* were readable by non-GIS programs unlike those from *r.out.gdal*. Similar experience, anyone? Perhaps, I just don't know how to configure *r.out.gdal* properly.

**Comment by HuidaeCho** [comment]
> I have used _r.out.tiff_ at one point because it handled color table differently than _r.out.gdal_. I think the colors in the TIFF from _r.out.tiff_ were readable by non-GIS programs unlike those from _r.out.gdal_. Similar experience, anyone? Perhaps, I just don't know how to configure _r.out.gdal_ properly.

That's a good point. Even if the same or similar color table is possible using _r.out.gdal_, but with more effort (e.g., complicated usage), I would prefer to keep _r.out.tiff_ or, maybe, rewrite it as a _r.out.gdal_ wrapper that implements the same interface.

**Comment by neteler** [comment]
> I have used _r.out.tiff_ at one point because it handled color table differently than _r.out.gdal_. I think the colors in the TIFF from _r.out.tiff_ were readable by non-GIS programs unlike those from _r.out.gdal_. Similar experience, anyone? 

Not really, do you have an example?

> Perhaps, I just don't know how to configure _r.out.gdal_ properly.

In the long run I'd prefer a working `r.out.gdal` over a rather abandoned `r.out.tiff`. The question is: is it a GRASS GIS or a GDAL problem?

**Review by lucadelu — APPROVED** [review]

**Comment by wenzeslaus** [comment]
> > I have used _r.out.tiff_ at one point because it handled color table differently than _r.out.gdal_. I think the colors in the TIFF from _r.out.tiff_ were readable by non-GIS programs unlike those from _r.out.gdal_. Similar experience, anyone?
> 
> Not really, do you have an example?

Isn't the difference _r.out.tiff_ exporting "colorful image" while _r.out.gdal_ exporting data with color table?

**Comment by neteler** [comment]
> > > I have used _r.out.tiff_ at one point because it handled color table differently than _r.out.gdal_. I think the colors in the TIFF from _r.out.tiff_ were readable by non-GIS programs unlike those from _r.out.gdal_. Similar experience, anyone?
> > 
> > 
> > Not really, do you have an example?
> 
> Isn't the difference _r.out.tiff_ exporting "colorful image" while _r.out.gdal_ exporting data with color table?

ok I see:

```
GRASS nc_spm_08_grass7/user1:~ > g.region raster=elevation
GRASS nc_spm_08_grass7/user1:~ > r.out.tiff input=elevation output=elevation.tif -w compression=lzw
WARNING: Raster map <elevation>> is a floating point map. Fractional values
         will be rounded to integer
 100%
Writing TIFF World file
r.out.tiff complete.

ls -1 elevation.t*
elevation.tfw
elevation.tif

display elevation.tif
```

I'll remove `r.out.tiff` from this PR.

**Review by wenzeslaus — APPROVED** [review]

**Comment by wenzeslaus** [comment]
BTW, @neteler, I think the same result as with a revert-redo operation could be achieved also with `git checkout master -- r.out.tiff` (it works with changed files, but I assume it would work with deleted dirs too).

**Review by HuidaeCho — APPROVED** [review]

**Review by landam — APPROVED** [review]

**Pull request merged**
