### PR TITLE
r.centroids testsuite

### PR DESCRIPTION
**Pull request by chaedri**
I've written a test module for r.centroids and fixed a typo in the manual page that prevented an image from rendering. 

The long string that I use to check the output of r.centroids against is not the most elegant solution. I tried assertVectorEqualsAscii() but consistently get an error that the strings don't match. I think it's related to GRASS running in Python 2 and the test running in Python 3 but I'm not sure. Any ideas welcome.

### CODE REVIEW

**Comment by marisn** [comment]
> The long string that I use to check the output of r.centroids against is not the most elegant solution. I tried assertVectorEqualsAscii() but consistently get an error that the strings don't match. I think it's related to GRASS running in Python 2 and the test running in Python 3 but I'm not sure. Any ideas welcome.

I am looking into my crystal ball and I see that you are using MS Windows. Your line of expected value seems to be completely wrong – it contains some '\r\r\n' crap – get rid of it and tests will start to work. If a multi-line output is expected, validate it line by line.

**Review by petrasovaa — CHANGES_REQUESTED** [review]
Also please remove the test_keyvalue_result.txt

**Comment by petrasovaa** [comment]
> > The long string that I use to check the output of r.centroids against is not the most elegant solution. I tried assertVectorEqualsAscii() but consistently get an error that the strings don't match. I think it's related to GRASS running in Python 2 and the test running in Python 3 but I'm not sure. Any ideas welcome.
> 
> I am looking into my crystal ball and I see that you are using MS Windows. Your line of expected value seems to be completely wrong – it contains some '\r\r\n' crap – get rid of it and tests will start to work. If a multi-line output is expected, validate it line by line.

I think you should be able to just format it like:
```
table = """642375|226865|2
643425|223335|4
642175|222595|6
...
"""
```

**Comment by petrasovaa** [comment]
Once the test_keyvalue_result.txt is removed, it is ready I think.

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
