### PR TITLE
g.citation: fix module output parameter

### PR DESCRIPTION
**Pull request by tmszi**
Fix module `output` parameter.

**Current behavior**

```bash
GRASS nc_spm_08_grass7/landsat:~ > g.citation v.surf.rst output=/tmp/result

GRASS nc_spm_08_grass7/landsat:~ > file /tmp/result
/tmp/result: cannot open `/tmp/result' (No such file or directory)
```

**Expected behavior:**

```bash
GRASS nc_spm_08_grass7/landsat:~ > g.citation v.surf.rst output=/tmp/result 

GRASS nc_spm_08_grass7/landsat:~ > cat /tmp/result 
@misc{v_surf_rst,
  title = {{GRASS GIS: v.surf.rst module}},
  author = {Lubos Mitas and Helena Mitasova and Irina Kosinovsky and Darrel McCauley and Jaroslav Hofierka and Stanislav Zubal and Michal Lacko},
  howpublished = {https://github.com/OSGeo/grass/tree/main/vector/v.surf.rst},
  year = {2022}
  note = {Accessed: 2022-10-16T07:02:16},
}

```

### CODE REVIEW

**Review by ninsbl — APPROVED** [review]
Looks good! Would be great if you could add _output_ to one of the tests, but no must...

**Review by ninsbl — APPROVED** [review]
Thanks for adding tests.
Tests fail with GRASS GIS 8.0 and Python 3.7, which can be expected, I guess, as 8.0 has different date formats in the manuals...
Not sure if it would be worth deactivating tests for 8.0...

**Comment by tmszi** [comment]
> Tests fail with GRASS GIS 8.0 and Python 3.7, which can be expected, I guess, as 8.0 has different date formats in the manuals... Not sure if it would be worth deactivating tests for 8.0...

The solution would be to backport this PR https://github.com/OSGeo/grass/pull/2595 to the releseabranch_8_0 branch.

**Comment by ninsbl** [comment]
> 



> The solution would be to backport this PR [OSGeo/grass#2595](https://github.com/OSGeo/grass/pull/2595) to the releseabranch_8_0 branch.

If that is straight forward to backport 8.0 as well, that sounds reasonable...

**Comment by wenzeslaus** [comment]
No need for a backport to 8.0. You can even remove 8.0 from grass-addons tests. The general policy is that we (as a project) support only the most recent release (individuals may decide to backport or even release and we may provide a limited support for that). (policy == something buried in minutes from some PSC meeting :-) please help!)

**Pull request merged**
