### PR TITLE
CI: add liblapacke-dev as dependency

### PR DESCRIPTION
**Pull request by nilason**
Add `liblapacke-dev` as dependency, to adopt to changes in GRASS GIS main.

### CODE REVIEW

**Comment by nilason** [comment]
Updates are needed for the cron jobs too.

**Comment by nilason** [comment]
> Updates are needed for the cron jobs too.

It not clear to me where this is run, and where its dependencies are declared. But `--with-blas-includes=/usr/include/atlas/` and `--with-lapack-includes=/usr/include/atlas/` are no longer valid configure flags.

**Comment by wenzeslaus** [comment]
Some, or hopefully all, of the code is in grass-addons. @neteler can comment more.

**Review by wenzeslaus — APPROVED** [review]

**Comment by neteler** [comment]
> Some, or hopefully all, of the code is in grass-addons. @neteler can comment more.

Installation of dependencies on grass.osgeo.org (DONE):

`neteler@grasslxd:~$ sudo apt install $(cat $HOME/src/main/.github/workflows/apt.txt)`

Flags need to be adjusted in the relevant `cron*.sh` scripts (TODO via PR):

https://github.com/OSGeo/grass-addons/tree/grass8/utils/cronjobs_osgeo_lxd/

**Pull request merged**
