### PR TITLE
r.landscape.evol: Fix incorrect number of seconds in a day

### LINKED ISSUE #1080: r.landscape.evol: Incorrect number of seconds in a day
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/OSGeo/grass-addons/blob/8135b8a7e919e816997f32f710b53a5af48362ce/src/raster/r.landscape.evol/r.landscape.evol.md?plain=1#L441

### PR DESCRIPTION
**Pull request by Pikamander2**
Fixes #1080

### CODE REVIEW

**Comment by echoix** [comment]
There's also the same change to do in the HTML file ;)

**Comment by Pikamander2** [comment]
@echoix - I've updated the other file now as well.

**Review by echoix — APPROVED** [review]
Perfect!

**Comment by echoix** [comment]
Thanks again! Oh, it's already merged!

**Pull request merged**
