### PR TITLE
New feature -  fixed encoding issue with stdin

### PR DESCRIPTION
**Pull request by isaacullah**
Fixed encoding issue with stdin for r.colors

### CODE REVIEW

**Comment by wenzeslaus** [comment]
@isaacullah You merged a r.catchment change as well. Please, describe the change and we can proceed from there to see how to handle that.

**Comment by isaacullah** [comment]
I merged a commit for r.catchment a few weeks ago, but haven't down
anything since... I was only working on r.landscape.evol this time. I'm not
sure why somehow r.catchment changes were also included with this one? I
may not have properly deleted the new-feature branch before this merge,
maybe? Nothing should have changed with r.catchment though. I'm not the
greatest with branching and merging in git. Sorry!

**Comment by isaacullah** [comment]
To clarify, all r.catchment modifications were done in #863. Nothing should have changed between then and now. I did not delete my fork after merging #863 and all the current modifications for r.lanscape.evol were done on the same fork as that one. So I am wondering if I should have deleted the fork after merging #863, and created a new fork for this current commit? Again, I am not the best with this stuff, so any advice is appreciated.

**Comment by wenzeslaus** [comment]
> I merged a commit for r.catchment a few weeks ago, but haven't down anything since...

You should review what you are merging in the _Files changed_ tab. Additionally, before merge, GitHub generates for you a commit message, a subject line and a body. Review those and edit. The auto-generated message includes all commit messages. That's not necessarily a useful final commit message for the merge, hence the edit, but it helps to see what you are merging.

> I was only working on r.landscape.evol this time. I'm not sure why somehow r.catchment changes were also included with this one?

You used your new-feature branch which had the r.catchment commits on it.

> I may not have properly deleted the new-feature branch before this merge, maybe?

Just use a new branch with a new name.

> To clarify, all r.catchment modifications were done in #863. Nothing should have changed between then and now.

The r.catchment changes were already included on the base branch (grass8). That's good then. They disappeared during the merge.

> I did not delete my fork after merging #863 and all the current modifications for r.lanscape.evol were done on the same fork as that one.

Deleting fork is useful when you made a mess and are not sure how to fix it (and you have all your work elsewhere). All you need to do is to create a new branch for every new change (change == PR in this context).

I can enable required reviews for PRs. Everyone with commit/merge/write access to grass-addons can give an approving review and we can agree that all what is needed is just general +1, not necessarily a full review, or we just go with standard reviews.

**Comment by isaacullah** [comment]
Thanks for the additional information @wenzeslaus. For the record, I was trying my best to follow the direction in [CONTRIBUTING.md](https://github.com/OSGeo/grass-addons/blob/grass8/CONTRIBUTING.md). Perhaps some of this additional information should be included there for posterity (I would do it, but clearly I am not the best one for that). I will be sure to create a new branch each time, update the commit message, and to check the "Files Changed Tab" from now on. All else sounds good.

**Comment by neteler** [comment]
> Thanks for the additional information @wenzeslaus. For the record, I was trying my best to follow the direction in [CONTRIBUTING.md](https://github.com/OSGeo/grass-addons/blob/grass8/CONTRIBUTING.md). Perhaps some of this additional information should be included there for posterity

Please send (either in a new PR or in a new issue) edit suggestions for CONTRIBUTING.md. This is highly welcome!

**Pull request merged**
