### PR TITLE
i.modis: support for MCD19A2 v006

### PR DESCRIPTION
**Pull request by landam**
This PR adds support for https://lpdaac.usgs.gov/products/mcd19a2v006/

### CODE REVIEW

**Comment by landam** [comment]
The input subsets in case of MCD19A2 contains more bands. 

Input data:
```
gdalinfo HDF4_EOS:EOS_GRID:"MCD19A2.A2020052.h18v03.006.2020056023047.hdf":grid1km:Optical_Depth_055
...
Band 1 Block=1200x833 Type=Int16, ColorInterp=Gray
  Description = AOD at 0.55 micron
    Computed Min/Max=0.000,597.000
  NoData Value=-28672
  Offset: 0,   Scale:0.001
Band 2 Block=1200x833 Type=Int16, ColorInterp=Gray
  Description = AOD at 0.55 micron
    Computed Min/Max=0.000,575.000
  NoData Value=-28672
  Offset: 0,   Scale:0.001
Band 3 Block=1200x833 Type=Int16, ColorInterp=Gray
  Description = AOD at 0.55 micron
    Computed Min/Max=0.000,519.000
  NoData Value=-28672
  Offset: 0,   Scale:0.001
Band 4 Block=1200x833 Type=Int16, ColorInterp=Gray
  Description = AOD at 0.55 micron
ERROR 1: HDF4_EOS:EOS_GRID:MCD19A2.A2020052.h18v03.006.2020056023047.hdf:grid1km:Optical_Depth_055, band 4: Failed to compute min/max, no valid pixels found in sampling.
  
  NoData Value=-28672
  Offset: 0,   Scale:0.001
Band 5 Block=1200x833 Type=Int16, ColorInterp=Gray
  Description = AOD at 0.55 micron
    Computed Min/Max=0.000,457.000
  NoData Value=-28672
  Offset: 0,   Scale:0.001
```

`i.modis.import` seems to import only the first channel

```
r.info -r MCD19A2.A2020052.h18v03.single_Optical_Depth_055
min=0
max=597
```

In this case we need average since it's combined product.

```
Orbit_amount=5
  Orbit_time_stamp=20200520915T  20200521055T  20200521105A  20200521230T  20200521245A
```

Ideally `i.modis.import` could have new parameter:

```
method   Aggregate operation
             options: average,minimum,maximum,...
```

But it would need modification also in pymodis library, right? @lucadelu Does it make sense to you?

**Comment by landam** [comment]
Temporary file already contains only one TIFF file.

```
gdalinfo MCD19A2.A2020052.h18v03.single_Optical_Depth_055.tif
...
Band 1 Block=1272x3 Type=Int16, ColorInterp=Gray
    Computed Min/Max=0.000,597.000
  NoData Value=-28672
```

**Comment by lucadelu** [comment]
> The input subsets in case of MCD19A2 contains more bands.
> 

ah, this is new for me

> Input data:
> 
> ```
> gdalinfo HDF4_EOS:EOS_GRID:"MCD19A2.A2020052.h18v03.006.2020056023047.hdf":grid1km:Optical_Depth_055
> ...
> Band 1 Block=1200x833 Type=Int16, ColorInterp=Gray
>   Description = AOD at 0.55 micron
>     Computed Min/Max=0.000,597.000
>   NoData Value=-28672
>   Offset: 0,   Scale:0.001
> Band 2 Block=1200x833 Type=Int16, ColorInterp=Gray
>   Description = AOD at 0.55 micron
>     Computed Min/Max=0.000,575.000
>   NoData Value=-28672
>   Offset: 0,   Scale:0.001
> Band 3 Block=1200x833 Type=Int16, ColorInterp=Gray
>   Description = AOD at 0.55 micron
>     Computed Min/Max=0.000,519.000
>   NoData Value=-28672
>   Offset: 0,   Scale:0.001
> Band 4 Block=1200x833 Type=Int16, ColorInterp=Gray
>   Description = AOD at 0.55 micron
> ERROR 1: HDF4_EOS:EOS_GRID:MCD19A2.A2020052.h18v03.006.2020056023047.hdf:grid1km:Optical_Depth_055, band 4: Failed to compute min/max, no valid pixels found in sampling.
>   
>   NoData Value=-28672
>   Offset: 0,   Scale:0.001
> Band 5 Block=1200x833 Type=Int16, ColorInterp=Gray
>   Description = AOD at 0.55 micron
>     Computed Min/Max=0.000,457.000
>   NoData Value=-28672
>   Offset: 0,   Scale:0.001
> ```
> 
> `i.modis.import` seems to import only the first channel
> 
> ```
> r.info -r MCD19A2.A2020052.h18v03.single_Optical_Depth_055
> min=0
> max=597
> ```
> 
> In this case we need average since it's combined product.
> 

so you have to calculate average of all the bands in the subset?

> ```
> Orbit_amount=5
>   Orbit_time_stamp=20200520915T  20200521055T  20200521105A  20200521230T  20200521245A
> ```
> 
> Ideally `i.modis.import` could have new parameter:
> 
> ```
> method   Aggregate operation
>              options: average,minimum,maximum,...
> ```
> 
> But it would need modification also in pymodis library, right? @lucadelu Does it make sense to you?

probably yes, do you have time to work on it? I'm a little be busy at the moment

**Comment by landam** [comment]
> probably yes, do you have time to work on it? I'm a little be busy at the moment

I will take a look...

**Comment by landam** [comment]
> > In this case we need average since it's combined product.
> 
> so you have to calculate average of all the bands in the subset?

Sorry for confusion. Average product can be computed afterwards by other GRASS commands.

For this issue it's important that all bands are imported into GRASS. See related changes in pymodis library https://github.com/lucadelu/pyModis/pull/129

**Comment by landam** [comment]
Replaced by #345

**Pull request closed without merging**
