### PR TITLE
Add insol_time parameter to r.sun.daily

### PR DESCRIPTION
**Pull request by PedroVenancio**
Add insol_time parameter to get the total insolation time between two dates.
Should close https://github.com/OSGeo/grass-addons/issues/325

### CODE REVIEW

**Review by lucadelu — COMMENTED** [review]
It seems fine to me, if the options are not used the addons works properly?

**Comment by PedroVenancio** [comment]
> It seems fine to me, if the options are not used the addons works properly?

Hi @lucadelu 

Thank you very much for check!

Do you mean if I compute raster outputs other than insol_time, like glob_rad or refl_rad? Yes, at least I didn't see any conflict until now.

**Comment by lucadelu** [comment]
@PedroVenancio next time please create a new branch to submit a pull request. (you can find some git/github info [here](https://trac.osgeo.org/grass/wiki/HowToGit) )

**Comment by PedroVenancio** [comment]
> next time please create a new branch to submit a pull request.

Sorry @lucadelu I will do that next time! Thank you very much!

**Pull request merged**
