### PR TITLE
i.eodag: additional options and modifications for i.sentinel.download

### PR DESCRIPTION
**Pull request by HamedElgizery**

### CODE REVIEW

**Comment by veroandreo** [comment]
@HamedElgizery do you plan to add more commits here or is the removal of the cloudcover value the only thing?

**Comment by HamedElgizery** [comment]
> @HamedElgizery do you plan to add more commits here or is the removal of the cloudcover value the only thing?

There will probably be a couple more additions.

**Comment by lucadelu** [comment]
@HamedElgizery why did you remove the answer? the default in eodag is all right?

**Comment by HamedElgizery** [comment]
> @HamedElgizery why did you remove the answer? the default in eodag is all right?

The default value messes up the filters for some products that doesn't have cloud coverage as a searching parameter i.e. S3_OLCI_L2WFR. In the case of S3_OLCI_L2WFR, it always returns 0 scenes found, instead of ignoring the clouds filter.

**Comment by HamedElgizery** [comment]
Branch was renamed to fix a typo, and another PR is open here: https://github.com/OSGeo/grass-addons/pull/1152

**Pull request closed without merging**
