### PR TITLE
g.extension/Windows: fix special characters

### PR DESCRIPTION
**Pull request by neteler**
This PR replaces numerous special characters g.extension on Windows is unable to deal with, as reported in https://github.com/OSGeo/grass/issues/1499.

The main problem appears to be ASCII vs UTF-8 encoding confusion.

### CODE REVIEW

**Comment by neteler** [comment]
It ideally fixes #525

**Comment by ninsbl** [comment]
Will have a look into this. Meanwhile see also:
https://github.com/OSGeo/grass-addons/issues/525#issuecomment-835774706

**Comment by neteler** [comment]
(fine for me to trash this PR if
we find a generic solution)

**Comment by nilason** [comment]
I think ASCII-alise the files, in particular the .py files, would be a step backwards and only used as a last resort. Hopefully the suggested update https://github.com/OSGeo/grass-addons/issues/525#issuecomment-835774706 will deal with the most urgent problems on Windows.
There are a lot of ascii encoded python files both in grass and grass-addons, which may be batch converted with iconv.

**Comment by hellik** [comment]
> I think ASCII-alise the files, in particular the .py files, would be a step backwards and only used as a last resort. Hopefully the suggested update [#525 (comment)](https://github.com/OSGeo/grass-addons/issues/525#issuecomment-835774706) will deal with the most urgent problems on Windows.
> There are a lot of ascii encoded python files both in grass and grass-addons, which may be batch converted with iconv.

In some Python addon scripts, there seems to be some mismatches between some (special) characters used and file encoding; this causes the crash in winGRASS g.extension.

Maybe an paragraph about to be more careful with file encoding of Python scripts and used (special) characters  should be added to the submitting guidelines?

In the example of i.fusion.hpf, it's just 1 quote character which isn't in line with the file encoding and causes the crash. 

Such things should be avoided while submitting an addon.

**Review by ninsbl — APPROVED** [review]
Regardles of possible changes in g.extensions, I tink this PR makes a lot of sense and increases consistency.

**Comment by hellik** [comment]
> Regardles of possible changes in g.extensions, I tink this PR makes a lot of sense and increases consistency.

Agreed here

**Comment by nilason** [comment]
> Regardles of possible changes in g.extensions, I tink this PR makes a lot of sense and increases consistency.

With regard to python files I disagree. This is just shovelling the dirt under the carpet. Proposed changes to g.extension actually make a whole lot of difference!

**Comment by neteler** [comment]
I'll close this since a better solution is in place.

**Pull request closed without merging**
