### PR TITLE
r.learn.train.py: changed sparse keyword in OneHotEncoder

### LINKED ISSUE #1175: r.learn.train: TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'
The CI fails with

```
scripts/r.learn.train:
`TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'`
```

_Originally posted in https://github.com/OSGeo/grass-addons/issues/1162#issuecomment-2277974535_

### PR DESCRIPTION
**Pull request by rohannallamadge**
Fix #1175:  deprecated keyword sparse changed to sparse_output

The keyword simply changed its name from `sparse` to `sparse_output`
Screenshot 2024-08-19 232858
Screenshot 2024-08-19 232744
Screenshot 2024-08-19 232715
Screenshot 2024-08-18 224606

### CODE REVIEW

**Comment by rohannallamadge** [comment]
sir after this what i should do

**Comment by rohannallamadge** [comment]
sir i have All checks have passed what to do after  this

**Comment by ecodiv** [comment]
This is in response to #1175 I presume? @neteler

**Comment by neteler** [comment]
@rohannallamadge Can you please edit PR title and description?

(Hint: I have added guidelines here: https://github.com/OSGeo/grass/pull/4197/files (they were missing from the contributing document). You may comment there if anything is yet unclear with the guidelines.)

**Comment by stevenpawley** [comment]
Thank you for this. Could you also change the requirement in `main` that checks for the scikit-learn version> We now need  scikit-learn >= 1.2.2.

**Comment by rohannallamadge** [comment]
sir actually don't know how to update or change  for the scikit-learn version

**Comment by ecodiv** [comment]
> sir actually don't know how to update or change for the scikit-learn version

Hi @rohannallamadge, in the file r.learn.train.py, look for 

```
    try:
        import sklearn

        if sklearn.__version__ < "0.20":
            gs.fatal("Package python3-scikit-learn 0.20 or newer is not installed")

    except ImportError:
        gs.fatal("Package python3-scikit-learn 0.20 or newer is not installed")
```

I think you just need to change the minimum version from "0.20" to "1.2.2"  (is that right @stevenpawley ?)

**Comment by rohannallamadge** [comment]
its already `scikit-learn version>`>=1.2.2 
Screenshot 2024-08-24 142556

**Comment by veroandreo** [comment]
> its already `scikit-learn version>`>=1.2.2 
> Screenshot 2024-08-24 142556
> 

@rohannallamadge what @ecodiv is saying is that you need to change the minimum required version in the source code of r.learn.train.

**Comment by rohannallamadge** [comment]
sir i have just changed #1175  from 0.20 to 1.2.2 in  file r.learn.train.py 
Screenshot 2024-08-25 011107

**Comment by neteler** [comment]
There is a CI issue:

```
Run DoozyX/clang-format-lint-action@caa179272c6ee7f1d25dfb503ee0c410c26ebd98
/usr/bin/docker run --name eba35c45d525ea4f047a28d8a4db79946ece5_3de2f8 --label 1eba35 --workdir /github/
[...]
Traceback (most recent call last):
  File "/run-clang-format.py", line 26, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```

Does @echoix have an idea how to fix that (seems unrelated to this PR).

**Comment by echoix** [comment]
Fixed this week in the same 20 hours, I interacted in that repo too.  So just re update the branch

**Comment by echoix** [comment]
@neteler do you have access to this repo's settings to always show to update the branch, not only on conflicts? (Like we have on the grass repo).

**Comment by rohannallamadge** [comment]
thanks @echoix  sir for helping me

**Review by echoix — APPROVED** [review]

**Pull request merged**
