### PR TITLE
Modifiy the branch for archival of v6 addons

### PR DESCRIPTION
**Pull request by wenzeslaus**
* Removes the grass7 subdirectory.
* Renames the grass6 subdiretcory to src.
* Updates readme.
* Adds a license.
* Removes GitHub configuration.

See the individual commits to review the changes rather than all changes in Changes.

### CODE REVIEW

**Comment by neteler** [comment]
Thanks for the initiative. The new branch https://github.com/wenzeslaus/grass-addons/tree/grass6 looks good to me.

The only changes (5 times) which I would suggest in `README.md` is

grass78 --> grass64

to reduce potential confusion.

**Comment by wenzeslaus** [comment]
> README...grass78 --> grass64

Done.

**Comment by wenzeslaus** [comment]
Does the rename of `grass6` subdirectory to `src` sound good in this case?

**Comment by neteler** [comment]
> Does the rename of `grass6` subdirectory to `src` sound good in this case?

Since it stays in its branch `grass6` it sounds fine to me.

**Comment by neteler** [comment]
May this be merged, @wenzeslaus? - then we can go ahead with the other addon branches which is a blocker for the GRASS GIS 8.0.0 release.

**Pull request merged**
