### PR TITLE
i.spec.sam manual: add description of the input matrix file containing signatures

### PR DESCRIPTION
**Pull request by YannChemin**
Added the description for the input matrix file containing the signatures (copied shamelessly from i.spec.unmix manual)

### CODE REVIEW

**Comment by neteler** [comment]
Please
- be so kind to (always) write PR titles using this style:<br> `module|topic: description`
- also set relevant label(s).

**Comment by echoix** [comment]
Keep in mind that outside collaborators, like me, can't add labels when creating PRs or change labels once the PR is made.

**Comment by neteler** [comment]
> Keep in mind that outside collaborators, like me, can't add labels when creating PRs or change labels once the PR is made.

I'm aware of this and Yann is core developer, afaik.

And for you we should change that :)

**Comment by echoix** [comment]
> > Keep in mind that outside collaborators, like me, can't add labels when creating PRs or change labels once the PR is made.
> 
> I'm aware of this and Yann is core developer, afaik.
> 
> And for you we should change that :)

Sorry, I didn't remember that name from the last two years following the projects when it passed by 😃

**Pull request merged**
