### PR TITLE
d.vect.scatter:  new addon to create scatterplots from vector data

### PR DESCRIPTION
**Pull request by ecodiv**
Draws a scatter plot or density scatter plot based on two columns in the attribute table of a vector layer. A linear or polynomial trend line can be added.

### CODE REVIEW

**Comment by petrasovaa** [comment]
See the naming discussion in #743. I do think the d.* is problematic, for the reasons mentioned in that discussion. I see you have v.scatterplot still in the documentation, I would think that would be better.

**Comment by ecodiv** [comment]
I tend to agree, as you may have guessed from the 'slip of tongue' in the documentation. However, for a consistent naming of related addons, I would suggest renaming the d.vect.hist and d.vect.colbp to v.histogram and v.boxplot as well. And perhaps even d.explanation.plot to r.explanation.plot? 

How would one rename addons while maintaining the history on git?

**Comment by nilason** [comment]
> How would one rename addons while maintaining the history on git?

Technically, it would be no more than a directory rename, e.g. `git mv display/d.vect.hist vector/v.histogram`. That singular change would ideally be one commit. Given the "squash before merge" policy of this repo, that means one pull request per addon rename.

**Comment by echoix** [comment]
> > How would one rename addons while maintaining the history on git?
> 
> 
> 
> Technically, it would be no more than a directory rename, e.g. `git mv display/d.vect.hist vector/v.histogram`. That singular change would ideally be one commit. Given the "squash before merge" policy of this repo, that means one pull request per addon rename.

GitHub is able to keep track of renames/moves of a little bit more than that, but there shouldn't be anything else than the rename/move in the same PR (if squashed). Not squashed, a commit also has to only have that operation. I tested this out a while back in the main repo https://github.com/OSGeo/grass/pull/2729#issue-1519309246

**Comment by ecodiv** [comment]
Not sure I follow 100%. Renaming need to be done after merging, and then a PR to rename?

On a related note, I would like to propose to rename the other above-mentioned addons. Any ideas about how to go about that. Is it enough if the original addon contributors agree?

**Comment by nilason** [comment]
> Not sure I follow 100%. Renaming need to be done after merging, and then a PR to rename?

You'll need two (!) PRs for one addon name change:

PR no. 1:
- `git mv ...`
- `git commit ...`
- `git push ..`
- create PR

PR no. 2 (after no 1 is merged):
- adapt the content of the addon to the new name
- create the new PR as usual

**Comment by petrasovaa** [comment]
> I tend to agree, as you may have guessed from the 'slip of tongue' in the documentation. However, for a consistent naming of related addons, I would suggest renaming the d.vect.hist and d.vect.colbp to v.histogram and v.boxplot as well. And perhaps even d.explanation.plot to r.explanation.plot?
> 
Yes, d.vect.colhist -> v.histogram and d.vect.colbp -> v.boxplot.
d.explanation.plot is actually a display tool, so that should be kept.

**Pull request merged**
