### PR TITLE
Apply Black

### PR DESCRIPTION
**Pull request by wenzeslaus**
- Black for vector
- Black for raster
- Black for temporal
- Black for imagery
- Black for gui
- Black for general
- Black for raster3d
- Black for display
- Black for db and misc
- Black for hadoop
- Add CI for Black
- Black for tools
- Config for Black

### CODE REVIEW

**Comment by wenzeslaus** [comment]
I will be more comfortable merging this with tests up and running again, so I will wait a bit with merge.

**Comment by neteler** [comment]
> I will be more comfortable merging this with tests up and running again, so I will wait a bit with merge.

I believe to have fixed it in #538 but not sure how to update this PR to make it realize the fix...

**Comment by nilason** [comment]
> > I will be more comfortable merging this with tests up and running again, so I will wait a bit with merge.
> 
> I believe to have fixed it in #538 but not sure how to update this PR to make it realize the fix...

Maybe a rebase is needed, to include the changes of #538?

**Comment by LorenzoBottaccioli** [comment]
In usage I get this waring, moreover` pyproj>2.2 `has no is_latlong(). 

```
UserWarning: 'is_latlong()' is deprecated. Please use 'crs.is_geographic'.
  warnings.warn("'is_latlong()' is deprecated. Please use 'crs.is_geographic'.")
```

**Pull request merged**
