### PR TITLE
utils/cronjobs_osgeo_lxd: allow register all addons keywords in main Keywords Index

### PR DESCRIPTION
**Pull request by tmszi**
Implement (closes) #776. Before apply this PR, you have to apply this GRASS GIS [PR](https://github.com/OSGeo/grass/pull/2529), please.

### CODE REVIEW

**Comment by neteler** [comment]
Thanks for implementing it, @tmszi ! I will test asap.

**Comment by neteler** [comment]
I could finally test this, sorry for the delay.

Very nice, we are almost there! E.g.

https://grass.osgeo.org/grass83/manuals/keywords.html#Sentinel
--> i.sentinel.* is listed.

The only thing to change is the URL: `/var/www/code_and_data/` leaks into it which comes from the usage of a related link on the build server, so:

https://grass.osgeo.org/var/www/code_and_data/grass83/manuals/addons/i.sentinel.coverage.html

should be

https://grass.osgeo.org/grass83/manuals/addons/i.sentinel.coverage.html

(likewise for all other addons).

**Comment by tmszi** [comment]
> I could finally test this, sorry for the delay.
> 
> Very nice, we are almost there! E.g.
> 
> https://grass.osgeo.org/grass83/manuals/keywords.html#Sentinel --> i.sentinel.* is listed.
> 
> The only thing to change is the URL: `/var/www/code_and_data/` leaks into it which comes from the usage of a related link on the build server, so:
> 
> https://grass.osgeo.org/var/www/code_and_data/grass83/manuals/addons/i.sentinel.coverage.html
> 
> should be
> 
> https://grass.osgeo.org/grass83/manuals/addons/i.sentinel.coverage.html
> 
> (likewise for all other addons).

Thanks Markus. This commit https://github.com/OSGeo/grass/pull/2529/commits/4fe3a0b1149cb0522d26bf505a0ac605e04a1cef solve it.

addons_man_page_relative_link

**Comment by neteler** [comment]
> Thanks Markus. This commit [OSGeo/grass@4fe3a0b](https://github.com/OSGeo/grass/commit/4fe3a0b1149cb0522d26bf505a0ac605e04a1cef) solve it.

Excellent, I have just tested it on the server and it works.
@ all: Please have a look if all manual/addon links work.

GRASS GIS 8 manual:
- main: https://grass.osgeo.org/grass83/manuals/
- Addons: https://grass.osgeo.org/grass83/manuals/addons/
- pygrass progman: https://grass.osgeo.org/grass83/manuals/libpython/

**Review by neteler — APPROVED** [review]

**Comment by neteler** [comment]
@tmszi seems a double `//` leaks in somewhere, only discovered that now.

**Comment by neteler** [comment]
> @tmszi seems a double `//` leaks in somewhere, only discovered that now.

I cleaned up the local server patches, updated and recompiled.

This effect only happens with the "grass-stable" redirects:

https://grass.osgeo.org/grass-stable/manuals/addons/d.vect.colbp.html
--> https://grass.osgeo.org/grass82//manuals/addons/d.vect.colbp.html

Probably it is an issue of the Apache redirect (but I think to not have seen it before).

**Comment by tmszi** [comment]
> > @tmszi seems a double `//` leaks in somewhere, only discovered that now.
> 
> I cleaned up the local server patches, updated and recompiled.
> 
> This effect only happens with the "grass-stable" redirects:
> 
> https://grass.osgeo.org/grass-stable/manuals/addons/d.vect.colbp.html --> https://grass.osgeo.org/grass82//manuals/addons/d.vect.colbp.html
> 
> Probably it is an issue of the Apache redirect (but I think to not have seen it before).

I found `//` in URL here https://grass.osgeo.org/grass82//manuals/index.html

**Comment by tmszi** [comment]
Could @neteler share Apache config/part of config (if it possible), please?

**Comment by neteler** [comment]
> Could @neteler share Apache config/part of config (if it possible), please?

Yes - I have sent it to you via personal email.

**Comment by tmszi** [comment]
> > Could @neteler share Apache config/part of config (if it possible), please?
> 
> Yes - I have sent it to you via personal email.

Ok. Thanks.

**Pull request merged**
