### PR TITLE
add option to i.sentinel.coverage

### PR DESCRIPTION
**Pull request by lucadelu**
@neteler, @anikaweinmann does it make sense to have producttype also here?

it was missing for my use case....

### CODE REVIEW

**Comment by anikaweinmann** [comment]
@lucadelu yes it would make sense. But for @griembauer and me it would make more sense, if the `type` would be replaced by the `producttype`.

**Comment by lucadelu** [comment]
Did I understand correctly?

**Comment by griembauer** [comment]
@lucadelu Thank you very much! I think this would also require some adaptions in the `scenename_split`-function. This function automatically pulls start and end date from the filename if a filename is provided by the user. However, this function can so far only handle S2-data and S1-GRD data - I am not sure how well it can handle S-1 `SLC` and `OCN` products.

**Comment by lucadelu** [comment]
@griembauer thanks to catch the problem in `scenename_split` I updated it. About the problem with S1 it seems more related to  the level of product, S1 Level 1 GRD and SLC should have the same name format that is different from S1 Level 2 GRD/SLC/OCN. But I think this is another problem that should not address in this pull request.

**Review by anikaweinmann — APPROVED** [review]
Thank you

**Comment by anikaweinmann** [comment]
> @griembauer thanks to catch the problem in `scenename_split` I updated it. About the problem with S1 it seems more related to the level of product, S1 Level 1 GRD and SLC should have the same name format that is different from S1 Level 2 GRD/SLC/OCN. But I think this is another problem that should not address in this pull request.

For me a new pull request later for this problem is fine

**Comment by lucadelu** [comment]
> > @griembauer thanks to catch the problem in `scenename_split` I updated it. About the problem with S1 it seems more related to the level of product, S1 Level 1 GRD and SLC should have the same name format that is different from S1 Level 2 GRD/SLC/OCN. But I think this is another problem that should not address in this pull request.
> 
> For me a new pull request later for this problem is fine

I created a new issue to not forget about it #413

**Pull request merged**
