### PR TITLE
cronjob: fix red new version box injection and script documentation

### PR DESCRIPTION
**Pull request by neteler**
This PR modifies the way to inject the "Note: This document is for an older version of GRASS GIS ..." red boxes into the manual page. Now duplicate boxes should no longer show up.

(affects G78 and G83 core manual and related addon manual pages)

- https://grass.osgeo.org/grass78/manuals/
- https://grass.osgeo.org/grass78/manuals/addons/
- https://grass.osgeo.org/grass83/manuals/
- https://grass.osgeo.org/grass83/manuals/addons/

For testing purposes, this PR has been deployed on grass.osgeo.org (once this PR is merged the local update needs to be removed from server to re-enable cronjob-based GH pulls, tbd by MN).

Hint: Best is to check how the pages look like not before Aug 17th, 2024, in order to have several daily cronjob cycles done.

### CODE REVIEW

**Comment by veroandreo** [comment]
* https://grass.osgeo.org/grass78/manuals/ --> red box is now in the header and footer of all pages (index, group and indiv manuals)
* https://grass.osgeo.org/grass78/manuals/addons/ --> red box is in the header and footer in indiv pages (index looks fine)
* https://grass.osgeo.org/grass83/manuals/ --> red box is now in the header and footer of all pages (index, group and indiv manuals)
* https://grass.osgeo.org/grass83/manuals/addons/ --> red box is in the header and footer in indiv pages (index looks fine)

Was this always the case to have the red box in the footer too?

**Review by wenzeslaus — DISMISSED** [review]
Can you please add a line or two describing what the commands are doing. Right now, the code is heavily write-only.

**Comment by neteler** [comment]
> Was this always the case to have the red box in the footer too?

As I said: Best is to check how the pages look like **not before Aug 17th**, 2024, in order to have several daily cronjob cycles done.

**Comment by veroandreo** [comment]
> > Was this always the case to have the red box in the footer too?
> 
> As I said: Best is to check how the pages look like **not before Aug 17th**, 2024, in order to have several daily cronjob cycles done.

Oh, ok, I understood that the PR should be checked before that date... sorry for the noise then :pray:

**Comment by neteler** [comment]
> Was this always the case to have the red box in the footer too?

No, it wasn't. In the overview pages the box was entirely missing.

Although I was surprised by the red box in the footer, on second thought it might not be so bad, especially for long pages. What do you think?

**Comment by veroandreo** [comment]
> > Was this always the case to have the red box in the footer too?
> 
> No, it wasn't. In the overview pages the box was entirely missing.
> 
> Although I was surprised by the red box in the footer, on second thought it might not be so bad, especially for long pages. What do you think?

I believe the one in the header is enough, no? That's the first thing one sees when opening a new page, and should be enough *warning*.

**Comment by echoix** [comment]
I saw some pages that had the header, but I stumbled upon one that only has a footer: https://grass.osgeo.org/grass83/manuals/variables.html

image
image


A page with header and footer: https://grass.osgeo.org/grass83/manuals/d.graph.html
image
image

**Comment by neteler** [comment]
Please re-check:

> * https://grass.osgeo.org/grass83/manuals/
> * https://grass.osgeo.org/grass83/manuals/addons/

I have uploaded a fix to the server. If ok, I'll submit it here and update this PR accordingly.

**Comment by veroandreo** [comment]
> Please re-check:
> 
> > * https://grass.osgeo.org/grass83/manuals/
> > * https://grass.osgeo.org/grass83/manuals/addons/
> 
> I have uploaded a fix to the server. If ok, I'll submit it here and update this PR accordingly.

looking good now!

**Comment by neteler** [comment]
Now also fixed (fix uploaded to the server for testing):

- https://grass.osgeo.org/grass78/manuals/
- https://grass.osgeo.org/grass78/manuals/addons/

**Comment by neteler** [comment]
> Can you please add a line or two describing what the commands are doing. Right now, the code is heavily write-only.

Sure: improved documentation of scripts in
- edb3cfa5aeed21f0db1f22c6476e644f9b06c60a (binary packages), and
- 54ee3cbd0b777228ce40b084d3f52026b898054d (source code packages)

**Comment by neteler** [comment]
"Merging is blocked" - I'd like to move on here.

Is anything still missing?

**Comment by echoix** [comment]
> "Merging is blocked" - I'd like to move on here.
> 
> 
> 
> Is anything still missing?

A requested changes by @wenzeslaus is still applied.

**Review by veroandreo — APPROVED** [review]

**Comment by neteler** [comment]
> A requested changes by @wenzeslaus is still applied.

I seem to need a hint.

**Review by wenzeslaus — COMMENTED** [review]
I agree with @echoix. I was indeed talking about documentation for the changed and complex lines. But I'm ready to move on here.

**Comment by neteler** [comment]
> A requested changes by @wenzeslaus is still applied.

Ok, see 1668170eb78564db5fec561889e1fb739d9ab71e

**Review by wenzeslaus — APPROVED** [review]
Thanks!

**Pull request merged**
