### PR TITLE
Add g.projpicker

### PR DESCRIPTION
**Pull request by HuidaeCho**
Add the ProjPicker (https://github.com/HuidaeCho/projpicker) wrapper.

```bash
pip3 install projpicker
```

### CODE REVIEW

**Comment by petrasovaa** [comment]
I haven't looked at this yet too much, but this will be most certainly very useful in location wizard. So what is the plan for integration in GUI? I think ultimately the projpicker code needs to go in core.

**Comment by nilason** [comment]
This is a really great addition! 👍

**Comment by HuidaeCho** [comment]
> I haven't looked at this yet too much, but this will be most certainly very useful in location wizard. So what is the plan for integration in GUI? I think ultimately the projpicker code needs to go in core.

@petrasovaa I have very limited knowledge about the GRASS GUI code, so at this point, I don't plan to implement a nice *GRASS GUI* around ProjPicker myself. However, this module already provides all the core features that the location wizard would need to implement what I envisioned initially in https://github.com/OSGeo/grass/issues/1253. The location wizard would
* allow the user to zoom, pan, and draw points or polygons in their area of interest,
* pass the coordinates of the input geometries to ProjPicker
* grab projection information (most importantly, `crs_auth_name`, `crs_code`, `unit`, `south_lat`, `north_lat`, `west_lon, and `east_lon`) from ProjPicker
* draw suggested projection extents on the GUI
* let the user select one desired projection

My standalone GUI project (`-g` flag) is more bare bones and tries to limit third-party modules to reduce dependencies.

We can certainly incorporate a snapshot of the core ProjPicker code as a single file or multiple files in the GRASS core. That was my goal when I initially wrote it as a single file, and it still is. Or maybe, better leave it as a standalone package? Anything is fine with me.

**Comment by HuidaeCho** [comment]
> This is a really great addition! +1

Thanks!

**Comment by petrasovaa** [comment]
> > I haven't looked at this yet too much, but this will be most certainly very useful in location wizard. So what is the plan for integration in GUI? I think ultimately the projpicker code needs to go in core.
> 
> @petrasovaa I have very limited knowledge about the GRASS GUI code, so at this point, I don't plan to implement a nice _GRASS GUI_ around ProjPicker myself. However, this module already provides all the core features that the location wizard would need to implement what I envisioned initially in [OSGeo/grass#1253](https://github.com/OSGeo/grass/issues/1253). The location wizard would
> 
> * allow the user to zoom, pan, and draw points or polygons in their area of interest,
> * pass the coordinates of the input geometries to ProjPicker
> * grab projection information (most importantly, `crs_auth_name`, `crs_code`, `unit`, `south_lat`, `north_lat`, `west_lon`, and `east_lon`) from ProjPicker
> * draw suggested projection extents on the GUI
> * let the user select one desired projection
> 
> My standalone GUI project (`-g` flag) is more bare bones and tries to limit third-party modules to reduce dependencies.
> 
> We can certainly incorporate a snapshot of the core ProjPicker code as a single file or multiple files in the GRASS core. That was my goal when I initially wrote it as a single file, and it still is. Or maybe, better leave it as a standalone package? Anything is fine with me.

Sounds good! I was not suggesting you need to do the GUI part, I was mainly curious about the code integration since you wrote it as separate tool. Unfortunately I don't have time now to develop the location wizard part.

**Comment by mlennert** [comment]
Am 13.06.2021 21:49 schrieb Huidae Cho:
>> I haven't looked at this yet too much, but this will be most
>> certainly very useful in location wizard. So what is the plan for
>> integration in GUI? I think ultimately the projpicker code needs to
>> go in core.
> 
> @petrasovaa [1] I have very limited knowledge about the GRASS GUI
> code, so at this point, I don't plan to implement a nice _GRASS GUI_
> around ProjPicker myself. However, this module already provides all
> the core features that the location wizard would need to implement
> what I envisioned initially in OSGeo/grass#1253 [2]. The location
> wizard would
> 
>  	* allow the user to zoom, pan, and draw points or polygons in their
> area of interest,
>  	* pass the coordinates of the input geometries to ProjPicker
>  	* grab projection information (most importantly, crs_auth_name,
> crs_code, unit, south_lat, north_lat, west_lon, and east_lon`) from
> ProjPicker
>  	* draw suggested projection extents on the GUI
>  	* let the user select one desired projection
> 
> My standalone GUI project (-g flag) is more bare bones and tries to
> limit third-party modules to reduce dependencies.
> 
> We can certainly incorporate a snapshot of the core ProjPicker code as
> a single file or multiple files in the GRASS core. That was my goal
> when I initially wrote it as a single file, and it still is. Or maybe,
> better leave it as a standalone package? Anything is fine with me.

Great addition !

Unless you have a specific need for this to continue to exist as a 
standalone package, I would encourage integrating it into the GRASS 
code. It just makes installation and maintenance easier.

**Comment by HuidaeCho** [comment]
> Unless you have a specific need for this to continue to exist as a standalone package, I would encourage integrating it into the GRASS code. It just makes installation and maintenance easier.

The ProjPicker project itself is not GRASS-specific, so there is a reason for it to be standalone and it would be easier for me to maintain it. However, I already have two other standalone projects that are integrated into the core ([libaprintf](https://github.com/HuidaeCho/libaprintf) and [cjkformat](https://github.com/HuidaeCho/cjkformat)), so it's not that big a deal for me. I'm just waiting until it's fully mature in terms for features. I'll integrate it into the core when it's ready.

**Comment by HuidaeCho** [comment]
For those who are interested, a new PR https://github.com/OSGeo/grass/pull/1770.

**Pull request merged**
