### PR TITLE
t.rast.import.netcdf: handle empty CRS and no subdataset

### LINKED ISSUE #1182: [Bug] t.rast.import.netcdf: Dataset object is not subscriptable
**Name of the addon**
t.rast.import.netcdf

**Describe the bug**
```
GRASS world_latlong_wgs84/PERMANENT:~ > t.rast.import.netcdf input="https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/netcdf/p05/chirps-v2.0.2011.days_p05.nc" output="chirps_2011" start_time="2011-01-01" end_time="2012-01-01" color="precipitation_daily" 
/usr/lib/python3/dist-packages/osgeo/gdal.py:287: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
Traceback (most recent call last):
  File "/home/vandreo/.grass8/addons/scripts/t.rast.import.netcdf", line 1228, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vandreo/.grass8/addons/scripts/t.rast.import.netcdf", line 1048, in main
    inputs_dict = [
                  ^
  File "/home/vandreo/.grass8/addons/scripts/t.rast.import.netcdf", line 1049, in <listcomp>
    parse_netcdf(
  File "/home/vandreo/.grass8/addons/scripts/t.rast.import.netcdf", line 791, in parse_netcdf
    sds_metadata = s_d[0].GetMetadata()
                   ~~~^^^
TypeError: 'Dataset' object is not subscriptable
```

**To Reproduce**
Run:
```
t.rast.import.netcdf input="https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/netcdf/p05/chirps-v2.0.2011.days_p05.nc" output="chirps_2011" start_time="2011-01-01" end_time="2012-01-01" color="precipitation_daily"
```

**System description:**
```
GRASS version: 8.5.0dev                                                         
Code revision: c53c938bac                                                       
Build date: 2024-08-04                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.7.1                                                                     
PROJ: 9.2.1                                                                     
GEOS: 3.12.0                                                                    
SQLite: 3.42.0                                                                  
Python: 3.11.6                                                                  
wxPython: 4.2.1                                                                 
Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.38                          
```

### PR DESCRIPTION
**Pull request by ninsbl**
This PR address various issues:
- NC files without CRS are now treated as CRS84 (default in GDAL)
- NC files without subdatasets were not handled properly
In addition, several formating issues were addressed...

### CODE REVIEW

**Comment by veroandreo** [comment]
I just tested with the same command reported in #1182 and I get:

```
r.in.gdal input=/vsicurl/https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_daily/netcdf/p05/chirps-v2.0.2011.days_p05.nc band=7 memory=300 offset=0 num_digits=0 output=chirps_v2_0_2011_days_p05_20110107T000000.convective_precipitation_rate -a --q
ERROR: Coordinate reference system of dataset does not appear to match
       current project.

       Project PROJ_INFO is:
       name: Lat/Lon
       proj: ll
       datum: wgs84
       ellps: wgs84
       init: EPSG:4326

       Dataset PROJ_INFO is:
       Dataset proj = 0 (unreferenced/unknown)

       Difference in: proj

       In case of no significant differences in the CRS definitions, use
       the -o flag to ignore them and use current project definition.
       Consider generating a new project from the input dataset using the
       'project' parameter.
Exception in thread Thread-7 (_handle_results):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CalledModuleError.__init__() missing 3 required positional arguments: 'module', 'code', and 'returncode'
```
and I need to Ctrl-C to stop it. I am not sure this is an issue of t.rast.import.netcdf or r.in.gdal. If I add the `-o` flag to override proj check, it goes fine.

**Comment by ninsbl** [comment]
Sorry, @veroandreo The CHIRPS dataset was a bit tricky. The upside is that it exposed a few other bugs in corner cases...

Now I added a test for CHIRPS as well and extended the testsuite.

That particular dataset may still cause trouble in praxis as the server seems very slow. It could be an advantage to download and import (or link) from there. That said, users must take care if reprojection is required on import (no -o flag). In that case the computational region has to be defined reasonably and the r-flag should probably be set (esp. when importing global data into projected CRS).... Added a few sentence on that in the manual...

**Comment by ninsbl** [comment]
Tests are failing due to version conflict in `cf_units`. It does not yet support NumPy 2, while CI uses NumPy 2.0. @echoix I saw you commented on a related issue in the cf_units repo. Should we try installing it from source in CI for the time beeing? The development version should support NumPy 2 and cf_units is only used in _t.rast.import.netcdf_ as far as I can see...

**Comment by echoix** [comment]
> Tests are failing due to version conflict in `cf_units`. It does not yet support NumPy 2, while CI uses NumPy 2.0. @echoix I saw you commented on a related issue in the cf_units repo. Should we try installing it from source in CI for the time beeing? The development version should support NumPy 2 and cf_units is only used in _t.rast.import.netcdf_ as far as I can see...

There might be hope, but we shouldn't count on this https://github.com/SciTools/cf-units/issues/438#issuecomment-2288286734

**Comment by ninsbl** [comment]
Tests pass locally. Is it OK to merge now and wait for cf_units to be updated? Then the improved / working module would become available. Tests should pass as soon as cf_units is NumPy 2 compatible... Will check that. We use the module in praxis and actually need the fix...

**Comment by ninsbl** [comment]
Taking the liberty to merge with tests failing due to version conflict in CI setup. Having the module working is needed. Tests will succeed when _cf_units_ supports _NumPy 2_...

**Pull request merged**
