### PR TITLE
r.forcircular: Evaluation of circular bioconomy level of forest ecosystems (GRASS GIS 7 version)

### PR DESCRIPTION
**Pull request by fra-lab**
Add the r.forcirculsr addon also for Grass 7.

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Looks good, merging.

**Comment by fra-lab** [comment]
Hi,
when I try to install r.forcircular on Grass 7.8.5 on Windows I obtain an error:
g.extension extension=r.forcircular                                             
Downloading precompiled GRASS Addons <r.forcircular>...
ERROR: Cannot open URL: http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.5/r.forcircular.zip

**Comment by ninsbl** [comment]
Unfortunately, there seems to be an issue with ctypes loader, that makes generation of the manual fail, which again causes that you cannot install the addon right now either:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.6/logs/r.forcircular.log

**Comment by ninsbl** [comment]
See: https://github.com/OSGeo/grass-addons/issues/691

**Comment by neteler** [comment]
> > Unfortunately, there seems to be an issue with ctypes loader, that makes generation of the manual fail, which again causes that you cannot install the addon right now either:
> > https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.6/logs/r.forcircular.log
> 
> I was quite quite surprised the other day when I figured out that docs/manual generation breaks the build of an addon/module. Yes, if the error is caused because the module has a runtime error, it's nice to catch it there since it's broken, but if it's the docs generation side that is broken, shouldn't we be able to at least build without?

Please note that during compilation the GRASS modules are actually *run* in order to generate the manual pages. In this case it is a ctypes error which is currently being addressed. Only then the manual can be generated (it used `module --html-description`).

**Comment by nilason** [comment]
According to log files it fails for 7.8.6, looking for libs in:

`C:\msys64\usr\src\grass786\dist.x86_64-w64-mingw32\lib`

while succeeds for [7.8.7dev](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/logs/r.forcircular.log), looking for libs in eg.:

`/usr/src/grass78/dist.x86_64-w64-mingw32/lib`

Note the difference in GRASS version number.

**Comment by wenzeslaus** [comment]
> ...it's nice to catch it there since it's broken, but if it's the docs generation side that is broken, shouldn't we be able to at least build without?

There is number of tradeoffs we can make here or there, but if we want to see if anything is broken, the build needs to fail in both cases.

In this particular case, the build environment is somehow incomplete which is exactly what we want to know about. On the other hand, modules can aim at running basic `grass.script.parser()` in an incomplete environment by lazy-importing anything which loads dynamic libraries (here _pygrass.raster_). This should be definitively done for 3rd party dependencies because it allows for build even when a dependency specific to one addon is not available in the build environment.

**Comment by fra-lab** [comment]
do I need to change something in the code to fix these problems?

**Comment by ninsbl** [comment]
> do I need to change something in the code to fix these problems?

No, unfortunately there is an underlying issue that needs to be fixed in the core or build system...

**Comment by ninsbl** [comment]
> while succeeds for [7.8.7dev](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/logs/r.forcircular.log), looking for libs in eg.:
> 
> `/usr/src/grass78/dist.x86_64-w64-mingw32/lib`


So conclusion is to get 7.8.7 out ASAP!?!

**Comment by neteler** [comment]
> So conclusion is to get 7.8.7 out ASAP!?!

Please test RC1, it is already there:
https://github.com/OSGeo/grass/releases/tag/7.8.7RC1

**Comment by nilason** [comment]
> > So conclusion is to get 7.8.7 out ASAP!?!
> 
> Please test RC1, it is already there: https://github.com/OSGeo/grass/releases/tag/7.8.7RC1

The problem is on Win only as it seems. Is there a RC1 for win somewhere?

**Comment by neteler** [comment]
> The problem is on Win only as it seems. Is there a RC1 for win somewhere?

I guess not. It would be great to let GHA generate it...

**Comment by ninsbl** [comment]
> > So conclusion is to get 7.8.7 out ASAP!?!
> 
> Please test RC1, it is already there: https://github.com/OSGeo/grass/releases/tag/7.8.7RC1

On MS Windows people usually need a packaged installer either in OSGeo4W or a standalone installer in order to test.
Neither seems available unfortunately, which hampers testing of pre-releases by the community. Something we should address somehow, IMHO... Maybe we could package in a github action?

**Comment by nilason** [comment]
There is always the latest:
https://wingrass.fsv.cvut.cz/grass78/x86_64/WinGRASS-7.8.7dev-7f6f550d7-1-Setup-x86_64.exe

Should be pretty much the same.

**Comment by fra-lab** [comment]
i installed grass 7.8.7dev (on Windows 10). I tried to install extension using the command menu setting/extension but the generation of the tree of extensions doesn't work.
If I try to manually install with g.extension r.forcircular I obtain this error message:
ERROR: Cannot open URL: http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/r.forcircular.zip

**Comment by echoix** [comment]
It's been how long since the first installation of grass or Python on this computer? Seems like this to me: https://github.com/OSGeo/grass/issues/2025#issuecomment-1003441506

Are you able to download demo data at the start screen (I wasn't able at that time)

What I find weird, is that when I did a clean install to Windows 11 in January, the same versions from OSGeo4w which I had until end of December, didn't have the problems I had with the new installation.

**Comment by fra-lab** [comment]
Usually I don't use Windows but several distro linux. My attempt was on a virtualbox virtual machine with windows 10 and an old previous installation of Grass (7.8.2) that I uninstalled before installing the 7.8.7dev

**Comment by echoix** [comment]
I'm still pretty sure that this is the same bug I had, old Python certificates or some things like that, since the URL exists. I assumed that the VM had internet access, of course haha.

**Pull request merged**
