### PR TITLE
r.extract: fix AttributeError 'append_random'

### PR DESCRIPTION
**Pull request by neteler**
fixes

```
r.extract input=some_map output=othermap cats=3 --o
Traceback (most recent call last):
  File "/home/mneteler/.grass7/addons/scripts/r.extract", line 116, in <module>
    sys.exit(main())
  File "/home/mneteler/.grass7/addons/scripts/r.extract", line 101, in main
    output_tmp = gs.append_random("tmp", 8)
AttributeError: module 'grass.script' has no attribute 'append_random'
```

### CODE REVIEW

**Comment by neteler** [comment]
Mhh, it still fails in GRASS GIS 7.8

**Comment by petrasovaa** [comment]
append_random is in master only

**Review by petrasovaa — CHANGES_REQUESTED** [review]
Please do it similarly as in https://github.com/OSGeo/grass-addons/blob/master/grass7/misc/m.csv.clean/m.csv.clean.py#L91.

That way we don't have to maintain twice the same functionality and the copy of the function can be later removed when not needed anymore.

**Comment by anikaweinmann** [comment]
@petrasovaa I changed it.

**Review by petrasovaa — APPROVED** [review]

**Pull request merged**
