### PR TITLE
r.prominence: update to G8 from GRASS GIS 6 version (#574)

### PR DESCRIPTION
**Pull request by nilason**
Manual port of #574 to grass8 branch.

* r.prominence: update from GRASS GIS 6 version

- updates https://github.com/OSGeo/grass-addons/tree/grass6/src/raster/r.prominence to GRASS GIS 7/8
- updates example to North Carolina sample data set
- shallow testing done, using the new example

Note: r.prominence appears to run very slowly, perhaps there is potential to optimize that

* cleanup leftover

* fix confusing error message

### CODE REVIEW

**Comment by neteler** [comment]
This is still on `grass*7*/raster/r.prominence/...`, perhaps to be moved?

**Comment by nilason** [comment]
> This is still on `grass*7*/raster/r.prominence/...`, perhaps to be moved?

I don't understand what you mean, where is what?

**Comment by neteler** [comment]
> I don't understand what you mean, where is what?

I was wondering about `grass7/` here, expecting `src/` if the `grass8` branch is targeted:

image

But maybe it's too late in my timezone :)

**Comment by nilason** [comment]
Ohh, you're right! It is probably my timezone ... Still a draft though :)

**Comment by nilason** [comment]
Maybe this can stay on grass7 branch, and I'll make another PR for grass8? This is clang-formatted, the other way around won't work anyway (with cherry-pick, that is).

**Comment by nilason** [comment]
Now I understand. The original code was merged to a state *before* the 'grass7' / 'grass8' split to 'src'. Will take a fresh look at this after a good nights rest.

**Comment by nilason** [comment]
Couldn't leave this be, turned out the easiest solution was to keep this PR destined to grass8. Should be good now.

**Comment by nilason** [comment]
Backported to grass7 with 8f28746c7c7d9dcd49ff2e5eec947ff0b7826b54.

**Pull request merged**
