### PR TITLE
rename database extension directory for grass7

### LINKED ISSUE #118: [Bug] Failure to install db.join
**Name of the addon**
db.join

**Describe the bug**
Trying to install db.join via the graphical g.extension results in an error. Installing other add-on modules (e.g. r.*) works. I guess it is a problem with the path (*/trunk/*); I don't know where this reference to svn comes from?!
```
Fetching <db.join> from GRASS GIS Addons repository (be patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-
addons/trunk/grass7/database/db.join' doesn't exist
ERROR: GRASS Addons <db.join> not found
```

**To Reproduce**
```
# Does not work
g.extension extension=db.join 
# Works                                                                           
g.extension extension=r.fuzzy.logic     
```                                        

**System description (please complete the following information):**
GRASS version: 7.9.dev                                                          
Code revision: 8eba412c8                                                        
Build date: 2020-02-27                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.1.0dev-c74609560e                                                       
PROJ: 6.2.1                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.5                                                                   
wxPython: 4.0.6                                                                 
Platform: Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan

### PR DESCRIPTION
**Pull request by ninsbl**
Should fix #118

### CODE REVIEW

**Comment by metzm** [comment]
There is no `grass-addons/grass7/database` directory, see https://github.com/OSGeo/grass-addons/tree/master/grass7. Maybe g.extension needs to be fixed?

**Comment by ninsbl** [comment]
This is how g.extension looks for database modules:
https://github.com/OSGeo/grass/blob/releasebranch_7_8/scripts/g.extension/g.extension.py#L201 and
https://github.com/OSGeo/grass/blob/releasebranch_7_8/scripts/g.extension/g.extension.py#L513

Thus, in order to have it consistent with all other modul classes, this PR renames the directory in the grass-addons repository…
That should also fix the link in the manual page that points to a "database" directory (https://github.com/OSGeo/grass-addons/tree/master/grass7/database/db.join) and not db...

**Comment by neteler** [comment]
Isn't it the other way around? When I change

```
--- a/scripts/g.extension/g.extension.py
+++ b/scripts/g.extension/g.extension.py
@@ -198,7 +198,7 @@ def expand_module_class_name(class_letters):
     """
     name = {
         'd': 'display',
-        'db': 'database',
+        'db': 'db',
         'g': 'general',
         'i': 'imagery',
         'm': 'misc',
```

the installation of the `db.join` addon works.

I'd rather keep the consistency of directory names between master and addons.

**Comment by ninsbl** [comment]
Yes, that is indeed another reasonable way to fix it (in g.extension).
Closing this one then.

**Pull request closed without merging**
