### PR TITLE
r.in.wcs improvements

### PR DESCRIPTION
**Pull request by lucadelu**

### CODE REVIEW

**Comment by ecodiv** [comment]
@neteler I'll check this weekend

**Comment by ecodiv** [comment]
Hi, as _posted by @lucadelu in https://github.com/OSGeo/grass-addons/issues/329#issuecomment-729631526_ getting the server capacilities works:

``` 
r.in.wcs url=http://maps.isric.org/mapserv?map=/map/cec.map -c
```
However, the following

```
r.in.wcs --verbose url=r.in.wcs url=http://maps.isric.org/mapserv? coverage=cec_0-5cm_mean output=AAtest01
```
Results in an error:

```
Importing raster map into GRASS...
Using current grass region
Boundingbox coordinates:
[33.0, 4.45, 39.4583333333333, 14.9]
[West, South, Eest, North]
gdalbuildvrt -te 33.0 4.45 39.4583333333333 14.9 -resolution user -tr 0.00208333333333333 0.00208333333333333 /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/180164.1 /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/180164.0
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: `/home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/180164.0' not recognized as a supported file format.
Warning 1: Can't open /home/paulo/Data/GRASSdb/latlon/WesternEthiopia/.tmp/HP-Z600/180164.0. Skipping it

ERROR: Generation of VRT-File failed (gdalbuildvrt ERROR). Set verbose-flag for details.
(Sat Nov 21 14:08:17 2020) Command finished (0 sec)                             
```

**Review by ecodiv — COMMENTED** [review]
I am not seeing any apparent problem with the code. But the addon is still failing, see my comment https://github.com/OSGeo/grass-addons/pull/340#issuecomment-731578071

**Comment by lucadelu** [comment]
I improved the code, it still doesn't work with that WCS server, probably for this problem https://gis.stackexchange.com/questions/361406/download-wrb-soil-groups/387839#387839

However it works with http://maps.isric.org/mapserv?map=/map/wrb.map

I suggest to merge the pull request since it improve WCS support

**Pull request merged**
