### PR TITLE
r.maxent.train: bugfix and clarification help text

### PR DESCRIPTION
**Pull request by ecodiv**
Fixes a bug and some small rewrites of help text

### CODE REVIEW

**Comment by neteler** [comment]
There is an unexpected `gs` file included (38 MB, apparently PDF). Accidentally committed?

**Comment by ecodiv** [comment]
Yes, not sure how that happened, definitely unintentional. Thanks for catching that, I'll remove it and check when back behind the computer.

**Comment by ecodiv** [comment]
@neteler Removed the gs file. Now one of the test fails. From the error message, I can't really see what is wrong, and whether there is a problem with my code. Do you have an idea?

**Comment by neteler** [comment]
The CI says " 7 successful checks" - which error do you mean?

**Comment by ecodiv** [comment]
> The CI says " 7 successful checks" - which error do you mean?

Sorry for the noise, there was an error, but running the checks again solved it, so apparently not related to my code/text.

**Pull request merged**
